function AnalysisFigure = Matching_MS_MLE_ChoiceForaging_Diagnosis(DataFolderPath)
% MS = MultiSession
% MLE = Maximum Likelihood Estimate
% Matching Analysis Function
% Developed by Antonio Lee @ BCCN Berlin
% Version 1.0 ~ Oct 2025
% Model iteration see the end of script

%% load files
if nargin < 1
    DataFolderPath = uigetdir(OttLabDataServerFolderPath());
elseif ~ischar(DataFolderPath) && ~isstring(DataFolderPath)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

try
    load(fullfile(DataFolderPath, '\Selected_Data.mat'));
    load(fullfile(DataFolderPath, '\Concatenated_Data.mat'));
catch
    disp('Error: Selected DataFolderPath does not contain the required .mat for further steps.')
    return
end

SessionDateRange = DataFolderPath(end-16:end);
[~, RatName] = fileparts(fileparts(fileparts(DataFolderPath)));

RatID = str2double(RatName);
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);

AnalysisName = 'Matching_MS_MLE_ChoiceForaging';

%% Hierarchaical Symmetric Q-Learning with Forgetting and Stickiness model
try
    load(fullfile(DataFolderPath, strcat('\', AnalysisName, '.mat')));
catch
    disp('Error: no models are found')
    return
end

if ~exist('Models', 'var')
    disp('Error: Loaded data is not a Models')
    return
end

%% create figure
% create figure
AnalysisFigure = figure('Position', [   0       0    1191     842],... % DIN A3, 72 ppi
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateRange, '_', AnalysisName),...
                        'MenuBar', 'none',...
                        'Resize', 'off');

% spacer for correct saving dimension
FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]);
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

% Figure Info
FigureInfoAxes = axes(AnalysisFigure, 'Position', [0.01    0.98    0.48    0.01]);
set(FigureInfoAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

FigureTitle = strcat(RatName, '_', SessionDateRange, '_', AnalysisName, '_Diagnosis');

FigureTitleText = text(FigureInfoAxes, 0, 0,...
                       FigureTitle,...
                       'FontSize', 14,...
                       'FontWeight','bold',...
                       'Interpreter', 'none');

% colour palette
ColourPalette = CommonColourPalette();

%% Analysis across sessions
SessionDateLabel = [];
nSessions = length(DataHolder);

% Posterior mode (i.e. MLE, maximum a posteriori) estimate of ChoiceSymmetricQ
% Photometry site vs non-photometry vs day-of-week (vs estrus if female)
MLEEstimateXTicks = {'all', 'non-photo', 'left-photo', 'right-photo'};

LearningRateMLEAxes = axes(AnalysisFigure, 'Position', [0.05    0.77    0.10    0.16]);
hold(LearningRateMLEAxes, 'on');

LearningRateMLEs = nan(1, nSessions);

set(LearningRateMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 4],...
    'XTick', 0:3,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(LearningRateMLEAxes, '\alpha (a.u.)')
title(LearningRateMLEAxes, 'MLE estimate')

InverseTemperatureMLEAxes = axes(AnalysisFigure, 'Position', [0.05    0.57    0.10    0.16]);
hold(InverseTemperatureMLEAxes, 'on');

InverseTemperatureMLEs = nan(1, nSessions);

set(InverseTemperatureMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 4],...
    'XTick', 0:3,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(InverseTemperatureMLEAxes, '\beta (a.u.)')

ForgettingRateMLEAxes = axes(AnalysisFigure, 'Position', [0.05    0.38    0.10    0.16]);
hold(ForgettingRateMLEAxes, 'on');

ForgettingRateMLEs = nan(1, nSessions);

set(ForgettingRateMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 4],...
    'XTick', 0:3,...
    'XTickLabel', MLEEstimateXTicks,...
    'XTickLabelRotation', 90,...
    'YAxisLocation', 'left')
ylabel(ForgettingRateMLEAxes, '\gamma_v (a.u.)')

ThresholdMLEAxes = axes(AnalysisFigure, 'Position', [0.20    0.77    0.10    0.16]);
hold(ThresholdMLEAxes, 'on');

ThresholdMLEs = nan(1, nSessions);

set(ThresholdMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 4],...
    'XTick', 0:3,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(ThresholdMLEAxes, '\theta (a.u.)')

%% residual distribution overview
SessionResidualDistributionAxes = axes(AnalysisFigure, 'Position', [0.35    0.15    0.64    0.09]);
hold(SessionResidualDistributionAxes, 'on')

SessionIdx = [];
Residuals = [];

set(SessionResidualDistributionAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [-1, 1],...
    'YAxisLocation', 'left')
ylabel(SessionResidualDistributionAxes, 'Residuals (a.u.)')

%% MLE overview
% inverse temperature
SessionLearningRateMLEAxes = axes(AnalysisFigure, 'Position', [0.35    0.86    0.64    0.10]);
hold(SessionLearningRateMLEAxes, 'on')

set(SessionLearningRateMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0, 1],...
    'YAxisLocation', 'left')
ylabel(SessionLearningRateMLEAxes, '\alpha (a.u.)')

% inverse temperature
SessionInverseTemperatureMLEAxes = axes(AnalysisFigure, 'Position', [0.35    0.74    0.64    0.10]);
hold(SessionInverseTemperatureMLEAxes, 'on')

set(SessionInverseTemperatureMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0, 10],...
    'YAxisLocation', 'left')
ylabel(SessionInverseTemperatureMLEAxes, '\beta (a.u.)')

% forgetting rate
SessionForgettingRateMLEAxes = axes(AnalysisFigure, 'Position', [0.35    0.62    0.64    0.10]);
hold(SessionForgettingRateMLEAxes, 'on')

set(SessionForgettingRateMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0, 1],...
    'YAxisLocation', 'left')
ylabel(SessionForgettingRateMLEAxes, '\gamma_v (a.u.)')

% choice stickiness
SessionThresholdMLEAxes = axes(AnalysisFigure, 'Position', [0.35    0.50    0.64    0.10]);
hold(SessionThresholdMLEAxes, 'on')

set(SessionThresholdMLEAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [-2, 1],...
    'YAxisLocation', 'left')
ylabel(SessionThresholdMLEAxes, '\theta (a.u.)')

%% SessionMeta
PhotometryRecordingTag = nan(1, length(DataHolder)); % 1: non-photo, 2:left, 3:right
WeekdayTag = nan(1, length(DataHolder)); %1: Sunday...

%% Plotting
for iSession = 1:length(DataHolder)
    % Import SessionData
    SessionData = DataHolder{iSession};
    SessionDateLabel = [SessionDateLabel, string(datestr(datetime(SessionData.Info.SessionDate), 'YYYYmmDD(ddd)'))];
    
    nTrials = SessionData.nTrials;
    if nTrials < 200
        disp(['Session ', num2str(iSession), ' has nTrial < 200. Impossible for analysis.'])
        continue
    end

    if ~isfield(SessionData.Custom.SessionMeta, 'PhotometryBrainArea')
        PhotometryRecordingTag(iSession) = 1;
    elseif contains(SessionData.Custom.SessionMeta.PhotometryBrainArea, 'eft')
        PhotometryRecordingTag(iSession) = 2;
    elseif contains(SessionData.Custom.SessionMeta.PhotometryBrainArea, 'ight')
        PhotometryRecordingTag(iSession) = 3;
    end
    WeekdayTag(iSession) = weekday(SessionData.Info.SessionDate);
    
    ChoiceLeft = SessionData.Custom.TrialData.ChoiceLeft(1:nTrials);
    Rewarded = SessionData.Custom.TrialData.Rewarded(1:nTrials);

    %% Analysis across sessions
    Model = Models{iSession};

    LearningRateMLEs(iSession) = Model.EstimatedParameters(1);
    InverseTemperatureMLEs(iSession) = Model.EstimatedParameters(2);
    ForgettingRateMLEs(iSession) = Model.EstimatedParameters(4);
    ThresholdMLEs(iSession) = Model.EstimatedParameters(3);
    
    MLEEstimates = [LearningRateMLEs(iSession), InverseTemperatureMLEs(iSession),...
                    ThresholdMLEs(iSession), ForgettingRateMLEs(iSession)];
    
    [NegLogDataLikelihood, Values] = ChoiceForaging(MLEEstimates, nTrials, ChoiceLeft, Rewarded);
    LogOdds = Values.ChoiceLeftLogOdds;
    
    PredictedLeftChoiceProb = 1 ./ (1 + exp(-LogOdds));

    PredictedChoice = double(PredictedLeftChoiceProb>=0.5);
    PredictedChoice(isnan(ChoiceLeft)) = nan;
    
    Explore = abs(ChoiceLeft - PredictedLeftChoiceProb) >= 0.5;
    Exploit = abs(ChoiceLeft - PredictedLeftChoiceProb) < 0.5;
    
    AbsModelResiduals = abs(ChoiceLeft - PredictedLeftChoiceProb);

    %% session residuals overview
    SessionIdx = [SessionIdx, iSession .* ones(1, nTrials)];
    Residuals = [Residuals, ChoiceLeft - PredictedLeftChoiceProb];
    
    %% session chain summary
    % learning rate
    LearningRateErrorBar(iSession) = errorbar(SessionLearningRateMLEAxes,...
                                              iSession,...
                                              MLEEstimates(1),...
                                              Model.ParameterStandardError(1),...
                                              'Marker', 'none',...
                                              'Color', 'k');
    % inverse temperature
    InverseTemperatureErrorBar(iSession) = errorbar(SessionInverseTemperatureMLEAxes,...
                                                    iSession,...
                                                    MLEEstimates(2),...
                                                    Model.ParameterStandardError(2),...
                                                    'Marker', 'none',...
                                                    'Color', 'k');

    % forgetting rate
    ForgettingRateErrorBar(iSession) = errorbar(SessionForgettingRateMLEAxes,...
                                                iSession,...
                                                MLEEstimates(4),...
                                                Model.ParameterStandardError(4),...
                                                'Marker', 'none',...
                                                'Color', 'k');

    % choice stickiness
    ThresholdErrorBar(iSession) = errorbar(SessionThresholdMLEAxes,...
                                           iSession,...
                                           MLEEstimates(3),...
                                           Model.ParameterStandardError(3),...
                                           'Marker', 'none',...
                                           'Color', 'k');
                                    
end

%% Average across sessions
% Posterior mode (i.e. MLE, maximum a posteriori) estimate of ChoiceSymmetricQ
XData = zeros(size(LearningRateMLEs));
LearningRateSwarmchart = swarmchart(LearningRateMLEAxes,...
                                    XData,...
                                    LearningRateMLEs,...
                                    'Marker', '.',...
                                    'MarkerEdgeColor', ColourPalette.Session,...
                                    'XJitter', 'density',...
                                    'XJitterWidth', 1);

LearningRateBoxchart = boxchart(LearningRateMLEAxes, XData, LearningRateMLEs);
set(LearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

PhotometryLearningRateSwarmchart = swarmchart(LearningRateMLEAxes,...
                                              PhotometryRecordingTag,...
                                              LearningRateMLEs,...
                                              'Marker', '.',...
                                              'MarkerEdgeColor', ColourPalette.Session,...
                                              'XJitter', 'density',...
                                              'XJitterWidth', 1);

PhotometryLearningRateBoxchart = boxchart(LearningRateMLEAxes, PhotometryRecordingTag, LearningRateMLEs);
set(PhotometryLearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

XData = zeros(size(InverseTemperatureMLEs));
InverseTemperatureSwarmchart = swarmchart(InverseTemperatureMLEAxes,...
                                          XData,...
                                          InverseTemperatureMLEs,...
                                          'Marker', '.',...
                                          'MarkerEdgeColor', ColourPalette.Session,...
                                          'XJitter', 'density',...
                                          'XJitterWidth', 1);

InverseTemperatureBoxchart = boxchart(InverseTemperatureMLEAxes, XData, InverseTemperatureMLEs);
set(InverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

PhotometryInverseTemperatureSwarmchart = swarmchart(InverseTemperatureMLEAxes,...
                                                    PhotometryRecordingTag,...
                                                    InverseTemperatureMLEs,...
                                                    'Marker', '.',...
                                                    'MarkerEdgeColor', ColourPalette.Session,...
                                                    'XJitter', 'density',...
                                                    'XJitterWidth', 1);

PhotometryInverseTemperatureBoxchart = boxchart(InverseTemperatureMLEAxes, PhotometryRecordingTag, InverseTemperatureMLEs);
set(PhotometryInverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

XData = zeros(size(ForgettingRateMLEs));
ForgettingRateSwarmchart = swarmchart(ForgettingRateMLEAxes,...
                                      XData,...
                                      ForgettingRateMLEs,...
                                      'Marker', '.',...
                                      'MarkerEdgeColor', ColourPalette.Session,...
                                      'XJitter', 'density',...
                                      'XJitterWidth', 1);

ForgettingRateBoxchart = boxchart(ForgettingRateMLEAxes, XData, ForgettingRateMLEs);
set(ForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

PhotometryForgettingRateSwarmchart = swarmchart(ForgettingRateMLEAxes,...
                                                PhotometryRecordingTag,...
                                                ForgettingRateMLEs,...
                                                'Marker', '.',...
                                                'MarkerEdgeColor', ColourPalette.Session,...
                                                'XJitter', 'density',...
                                                'XJitterWidth', 1);

PhotometryForgettingRateBoxchart = boxchart(ForgettingRateMLEAxes, PhotometryRecordingTag, ForgettingRateMLEs);
set(PhotometryForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

XData = zeros(size(ThresholdMLEs));
ThresholdSwarmchart = swarmchart(ThresholdMLEAxes,...
                                 XData,...
                                 ThresholdMLEs,...
                                 'Marker', '.',...
                                 'MarkerEdgeColor', ColourPalette.Session,...
                                 'XJitter', 'density',...
                                 'XJitterWidth', 1);

ThresholdBoxchart = boxchart(ThresholdMLEAxes, XData, ThresholdMLEs);
set(ThresholdBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

PhotometryThresholdSwarmchart = swarmchart(ThresholdMLEAxes,...
                                           PhotometryRecordingTag,...
                                           ThresholdMLEs,...
                                           'Marker', '.',...
                                           'MarkerEdgeColor', ColourPalette.Session,...
                                           'XJitter', 'density',...
                                           'XJitterWidth', 1);

PhotometryThresholdBoxchart = boxchart(ThresholdMLEAxes, PhotometryRecordingTag, ThresholdMLEs);
set(PhotometryThresholdBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

%% Session residuals overview
SessionResidualsSwamchart = swarmchart(SessionResidualDistributionAxes,...
                                       SessionIdx,...
                                       Residuals,...
                                       'Marker', '.',...
                                       'MarkerEdgeColor', ColourPalette.Session,...
                                       'XJitter', 'density',...
                                       'XJitterWidth', 1);


set(SessionResidualDistributionAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', SessionDateLabel,...
    'XTickLabelRotation', 90);

%% session MLE overview
SesionDateDatetime = datetime(SessionDateLabel, 'InputFormat', 'yyyyMMdd(eee)');
SessionDateDiffDays = caldays(caldiff(SesionDateDatetime, 'days'));
WaterDeprivedDayOneIdx = [1, find(SessionDateDiffDays > 1) + 1];

% forgetting rate
SessionLearningRateMLEPlot = plot(SessionLearningRateMLEAxes, 1:nSessions, LearningRateMLEs,...
                                  'Marker', 'o',...
                                  'MarkerIndices', WaterDeprivedDayOneIdx,...
                                  'Color', 'k');

set(SessionLearningRateMLEAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

% forgetting rate
SessionInverseTemperatureMLEPlot = plot(SessionInverseTemperatureMLEAxes, 1:nSessions, InverseTemperatureMLEs,...
                                        'Marker', 'o',...
                                        'MarkerIndices', WaterDeprivedDayOneIdx,...
                                        'Color', 'k');

set(SessionInverseTemperatureMLEAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

% forgetting rate
SessionForgettingRateMLEPlot = plot(SessionForgettingRateMLEAxes, 1:nSessions, ForgettingRateMLEs,...
                                    'Marker', 'o',...
                                    'MarkerIndices', WaterDeprivedDayOneIdx,...
                                    'Color', 'k');

set(SessionForgettingRateMLEAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

% threshold
SessionThresholdMLEPlot = plot(SessionThresholdMLEAxes, 1:nSessions, ThresholdMLEs,...
                               'Marker', 'o',...
                               'MarkerIndices', WaterDeprivedDayOneIdx,...
                               'Color', 'k');

set(SessionThresholdMLEAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

DataPath = strcat(DataFolderPath, '\', FigureTitle, '.png');
exportgraphics(AnalysisFigure, DataPath);

DataPath = strcat(DataFolderPath, '\', FigureTitle, '.fig');
savefig(AnalysisFigure, DataPath);

end % function