function TwoArmBanditVariant_Cued_MultiSession_Analysis(DataFolderPath)
%{
First create on 20230622 by Antonio Lee for AG Ott @HU Berlin
With the file server architecture, this functions runs through the
session folders of the designated Animals after a PeriodStartDate and before a
PeriodEndDate to parse out the TrialData necessary for Analysis.m

V2.0 20240515 dedicated script for analyzing multiple sessions with similar
settings (no checking is done). A folder is selected instead of a .mat file
(so that a bit of back and forth looking at the concatenated data and
individual session data is allowed)

The analysis is positioned to only look at the data descriptively,
particularly identifying any indication of which some sessions are not, or
some trials are not comparable with the others (head and tail)
%}

if nargin < 1
    DataFolderPath = uigetdir(OttLabDataServerFolderPath());
elseif ~ischar(DataFolderPath) && ~isstring(DataFolderPath)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

try
    load(fullfile(DataFolderPath, '\Selected_Data.mat'));
    load(fullfile(DataFolderPath, '\Concatenated_Data.mat'));
catch
    disp('Error: Selected DataFolderPath does not contain the required .mat for further steps.')
    return
end

SessionDateRange = DataFolderPath(end-16:end);
[~, RatName] = fileparts(fileparts(fileparts(DataFolderPath)));

RatID = str2double(RatName);
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);

AnalysisName = 'Cued_MultiSession_Analysis';

%% Check if all sessions are of the same SettingsFile
%{
% not sure how to best do it yet, as some settings are drawn in each trial
and displayed
for iSession = 1:length(DataHolder)
    SessionData = DataHolder{iSession};

    if ~isfield(SessionData, 'SettingsFile')
        disp('Error: The selected file does not have the field "SettingsFile". No further Matching Analysis is performed.')
        AnalysisFigure = [];
        return
    elseif ~isfield(SessionData.SettingsFile.GUIMeta, 'RiskType')
        disp('Error: The selected SessionFile may not be a TwoArmBanditVariant session. No further Matching Analysis is performed.')
        AnalysisFigure = [];
        return
    elseif ~strcmpi(SessionData.SettingsFile.GUIMeta.RiskType.String{SessionData.SettingsFile.GUI.RiskType}, 'BlockFixHolding')
        disp('Error: The selected SessionData is not a Matching session. No further Matching Analysis is performed.')
        AnalysisFigure = [];
        return
    end
end
%}
    
%% Common plots regardless of task design/ risk type
% colour palette for events (suitable for most colourblind people)
scarlet = [254, 60, 60]/255; % for incorrect sign, contracting with azure
denim = [31, 54, 104]/255; % mainly for unsuccessful trials
azure = [0, 162, 254]/255; % for rewarded sign

neon_green = [26, 255, 26]/255; % for NotBaited
neon_purple = [168, 12, 180]/255; % for SkippedBaited

sand = [225, 190 106]/255; % for left-right
turquoise = [64, 176, 166]/255;
LRPalette = [sand; turquoise];

% colour palette for cues: (1- P(r)) * 128 + 127
% P(0) = white; P(1) = smoky gray
% RewardProbCategories = unique(RewardProb);
% CuedPalette = ((1 - RewardProbCategories) * [128 128 128] + 127)/255;

%{
if p.TimelineView
    EarliestSessionDate = datetime(DataHolder{1}.Info.SessionDate);
    LatestSessionDate = datetime(DataHolder{end}.Info.SessionDate);
    FullDateRange = between(EarliestSessionDate, LatestSessionDate, 'Days');
    FullDateRangeChar = char(FullDateRange);
    ColourAdjustmentDenominator = str2double(FullDateRangeChar(1:end-1));
else
    ColourAdjustmentDenominator = size(DataHolder);
end
%}

%% Initiatize figure
% create figure
AnalysisFigure = figure('Position', [   0       0    1191     842],... % DIN A3, 72 ppi
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateRange, '_', AnalysisName),...
                        'MenuBar', 'none',...
                        'Resize', 'off');

% spacer for correct saving dimension
FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]);
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

% Figure Info
FigureInfoAxes = axes(AnalysisFigure, 'Position', [0.01    0.98    0.48    0.01]);
set(FigureInfoAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

FigureTitle = strcat(RatName, '_', SessionDateRange, '_', AnalysisName);

FigureTitleText = text(FigureInfoAxes, 0, 0,...
                       FigureTitle,...
                       'FontSize', 14,...
                       'FontWeight','bold',...
                       'Interpreter', 'none');

%% Analysis across trials
% NoTrialStart Rate across session
NoTrialStartAxes = axes(AnalysisFigure, 'Position', [0.01    0.84    0.37    0.11]);
hold(NoTrialStartAxes, 'on');

NoTrialStartYData = ones(100, 2000) * 100;

set(NoTrialStartAxes,...
    'TickDir', 'out',...
    'YLim', [0 100],...
    'YTick', [0 50 100],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
xlabel(NoTrialStartAxes, 'iTrial')
ylabel(NoTrialStartAxes, 'NoTrialStart (%)')

% WithChoice Rate across session
WithChoiceAxes = axes(AnalysisFigure, 'Position', [0.01    0.67    0.37    0.11]);
hold(WithChoiceAxes, 'on');

WithChoiceYData = zeros(100, 2000);

set(WithChoiceAxes,...
    'TickDir', 'out',...
    'XTickLabel', {},...
    'XAxisLocation', 'top',...
    'YLim', [0 100],...
    'YTick', [0 50 100],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel(WithChoiceAxes, 'WithChoice (%)')

%% Analysis across sessions
SessionDateLabel = [];

% Active Time (SessionDuration - any break > 5 minutes)
ActiveTimeAxes = axes(AnalysisFigure, 'Position', [0.53    0.84    0.42    0.11]);
hold(ActiveTimeAxes, 'on');

set(ActiveTimeAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 4],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel(ActiveTimeAxes, 'Active Time (h)')

% Total Water Consumption and Rate
WaterConsumptionAxes = axes(AnalysisFigure, 'Position', [0.53    0.71    0.42    0.11]);
hold(WaterConsumptionAxes, 'on');

set(WaterConsumptionAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 15],...
    'FontSize', 10);
ylabel(WaterConsumptionAxes, 'Consumed Water (mL)')

yyaxis(WaterConsumptionAxes, 'right')
set(WaterConsumptionAxes,...
    'YLim', [0 4],...
    'FontSize', 10);
ylabel(WaterConsumptionAxes, 'Rate (mL h^{-1})')

% Left-Right Move Time
LRMoveTimeAxes = axes(AnalysisFigure, 'Position', [0.53    0.58    0.42    0.11]);
hold(LRMoveTimeAxes, 'on');

set(LRMoveTimeAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 1],...
    'YAxisLocation', ' right',...
    'FontSize', 10);
ylabel(LRMoveTimeAxes, 'MoveTime (s)')

% Left-Right Time Investment (NotBaited Waiting Time)
LRTIAxes = axes(AnalysisFigure, 'Position', [0.53    0.45    0.42    0.11]);
hold(LRTIAxes, 'on');

set(LRTIAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTick', [],...
    'YLim', [0 12],...
    'YAxisLocation', ' right',...
    'FontSize', 10);
ylabel(LRTIAxes, 'Time Investment (s)')

% Trial Length
TrialLengthAxes = axes(AnalysisFigure, 'Position', [0.53    0.32    0.42    0.11]);
hold(TrialLengthAxes, 'on');

set(TrialLengthAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 30],...
    'YAxisLocation', ' right',...
    'FontSize', 10);
ylabel(TrialLengthAxes, 'Trial Length (s)')

% SkippedBaited Rate across session
SkippedBaitedAxes = axes(AnalysisFigure, 'Position', [0.53    0.19    0.42    0.11]);
hold(SkippedBaitedAxes, 'on');

set(SkippedBaitedAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 15],...
    'YTick', [0 5 10],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel(SkippedBaitedAxes, 'SkippedBaited (%)')

% Cue-sorted Move Time
CueSortedMoveTimeAxes = axes(AnalysisFigure, 'Position', [0.01    0.32    0.42    0.11]);
hold(CueSortedMoveTimeAxes, 'on');

CueSortedMoveTimeSwarmchart = {};
CueSortedMoveTimeBoxchart = {};

set(CueSortedMoveTimeAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 1],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel(CueSortedMoveTimeAxes, 'Move Time (s)')

% Cue-sorted Time Investment (NotBaited Waiting Time)
CueSortedTIAxes = axes(AnalysisFigure, 'Position', [0.01    0.19    0.42    0.11]);
hold(CueSortedTIAxes, 'on');

CueSortedTISwarmchart = {};
CueSortedTIBoxchart = {};

set(CueSortedTIAxes,...
    'TickDir', 'in',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [0 15],...
    'YTick', [0 5 10],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel(CueSortedTIAxes, 'Time Investment (s)')

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

%% Plotting
for iSession = 1:length(DataHolder)
    % Import SessionData
    SessionData = DataHolder{iSession};
    SessionDateLabel = [SessionDateLabel, string(datestr(datetime(SessionData.Info.SessionDate), 'YYYYmmDD(ddd)'))];
    
    nTrials = SessionData.nTrials;
    if nTrials < 200
        disp(['Session ', num2str(iSession), ' has nTrial < 200. Impossible for analysis.'])
        continue
    end
    
    ChoiceLeft = SessionData.Custom.TrialData.ChoiceLeft(1:nTrials);
    Baited = SessionData.Custom.TrialData.Baited(:, 1:nTrials);
    IncorrectChoice = SessionData.Custom.TrialData.IncorrectChoice(1:nTrials);
    NoDecision = SessionData.Custom.TrialData.NoDecision(1:nTrials);
    NoTrialStart = SessionData.Custom.TrialData.NoTrialStart(1:nTrials);
    BrokeFixation = SessionData.Custom.TrialData.BrokeFixation(1:nTrials);
    EarlyWithdrawal = SessionData.Custom.TrialData.EarlyWithdrawal(1:nTrials);
    StartNewTrial = SessionData.Custom.TrialData.StartNewTrial(1:nTrials);
    SkippedFeedback = SessionData.Custom.TrialData.SkippedFeedback(1:nTrials);
    Rewarded = SessionData.Custom.TrialData.Rewarded(1:nTrials);
    
    SampleTime = SessionData.Custom.TrialData.SampleTime(1:nTrials);
    MoveTime = SessionData.Custom.TrialData.MoveTime(1:nTrials);
    FeedbackWaitingTime = SessionData.Custom.TrialData.FeedbackWaitingTime(1:nTrials);
    % FeedbackDelay = SessionData.Custom.TrialData.FeedbackDelay(1:nTrials);
    % FeedbackWaitingTime = rand(nTrials,1)*10; %delete this
    % FeedbackWaitingTime = FeedbackWaitingTime';  %delete this
    % FeedbackDelay = rand(nTrials,1)*10; %delete this
    % FeedbackDelay= FeedbackDelay'; 
    
    RewardProb = SessionData.Custom.TrialData.RewardProb(:, 1:nTrials);
    LightLeft = SessionData.Custom.TrialData.LightLeft(1:nTrials);
    LightLeftRight = [LightLeft; 1-LightLeft]; 
    ChoiceLeftRight = [ChoiceLeft; 1-ChoiceLeft]; 
    
    BlockNumber = SessionData.Custom.TrialData.BlockNumber(:, 1:nTrials);
    BlockTrialNumber = SessionData.Custom.TrialData.BlockTrialNumber(:, 1:nTrials);
    
    % for files before April 2023, no DrinkingTime is available
    try
        DrinkingTime = SessionData.Custom.TrialData.DrinkingTime(1:nTrials);
    catch
        DrinkingTime = nan(1, nTrials);
    end
    
    LeftFeedbackDelayGraceTime = [];
    RightFeedbackDelayGraceTime = [];
    FirstDrinkingTime = [];
    LatestRewardTimestamp = [];
    for iTrial = 1:nTrials
        if ChoiceLeft(iTrial) == 1
            LeftFeedbackDelayGraceTime = [LeftFeedbackDelayGraceTime;...
                                          SessionData.RawEvents.Trial{iTrial}.States.LInGrace(:,2) -...
                                          SessionData.RawEvents.Trial{iTrial}.States.LInGrace(:,1)];
        elseif ChoiceLeft(iTrial) == 0
            RightFeedbackDelayGraceTime = [RightFeedbackDelayGraceTime;...
                                           SessionData.RawEvents.Trial{iTrial}.States.RInGrace(:,2) -...
                                           SessionData.RawEvents.Trial{iTrial}.States.RInGrace(:,1)];
        end
        
        FirstDrinkingTime = [FirstDrinkingTime SessionData.RawEvents.Trial{iTrial}.States.Drinking(1,1)];
        if iTrial == 1
            LatestRewardTimestamp(iTrial) = 0;
        elseif isnan(SessionData.RawEvents.Trial{iTrial-1}.States.Drinking(1,1))
            LatestRewardTimestamp(iTrial) = LatestRewardTimestamp(iTrial-1);
        else
            LatestRewardTimestamp(iTrial) = SessionData.RawEvents.Trial{iTrial-1}.States.Drinking(1,1) + SessionData.TrialStartTimestamp(iTrial-1);
        end
    end
    LatestRewardTime = SessionData.TrialStartTimestamp - LatestRewardTimestamp;
    
    LeftFeedbackDelayGraceTime = LeftFeedbackDelayGraceTime(~isnan(LeftFeedbackDelayGraceTime))';
    LeftFeedbackDelayGraceTime = LeftFeedbackDelayGraceTime(LeftFeedbackDelayGraceTime < SessionData.SettingsFile.GUI.FeedbackDelayGrace - 0.0001);
    RightFeedbackDelayGraceTime = RightFeedbackDelayGraceTime(~isnan(RightFeedbackDelayGraceTime))';
    RightFeedbackDelayGraceTime = RightFeedbackDelayGraceTime(RightFeedbackDelayGraceTime < SessionData.SettingsFile.GUI.FeedbackDelayGrace - 0.0001);
    
    RewardMagnitude = SessionData.Custom.TrialData.RewardMagnitude(:, 1:nTrials);
    TrialStartTimeStamp = SessionData.TrialStartTimestamp;
    TrialEndTimeStamp = SessionData.TrialEndTimestamp;

    idxTrial = 1:nTrials;
    SessionColor = [1, 1, 1] * 0.85; % ([1, 1, 1] - iSession / length(DataHolder)) * 0.9;
    
    %% Analysis across trials
    % NoTrialStart Rate across session
    NoTrialStartLine{iSession} = line(NoTrialStartAxes,...
                                      'xdata', idxTrial,...
                                      'ydata', smooth(movmean(NoTrialStart, [10 9])) * 100,...
                                      'LineStyle', '-',...
                                      'Marker', 'none',...
                                      'Color', SessionColor);
    
    NoTrialStartYData(iSession, 1:length(NoTrialStart)) = NoTrialStart * 100;
    
    % WithChoice Rate across session
    WithChoiceRate = ~isnan(ChoiceLeft);
    WithChoiceLine{iSession} = line(WithChoiceAxes,...
                                    'xdata', idxTrial,...
                                    'ydata', smooth(movmean(WithChoiceRate, [10 9])) * 100,...
                                    'LineStyle', '-',...
                                    'Marker', 'none',...
                                    'Color', SessionColor);
    
    WithChoiceYData(iSession, 1:length(ChoiceLeft)) = WithChoiceRate * 100;
    
    %% Analysis across sessions
    % Active Time (Total SessionDuration - any break > 5 minutes)
    NonActiveNess = movmean(NoTrialStart, [0 19]); % should correspond to 5 minutes
    NonActiveIdx = find(NonActiveNess == 1);

    ActiveTrial = ones(size(NoTrialStart));
    if ~isempty(NonActiveIdx)
        for iNonActiveIdx = 1:length(NonActiveIdx)
            ActiveTrial(iNonActiveIdx:iNonActiveIdx+19) = 0;
        end
    end

    TrialLength = TrialEndTimeStamp - TrialStartTimeStamp;
    SessionDuration = sum(TrialLength(ActiveTrial == 1)) / 3600;

    ActiveTimeLine{iSession} = line(ActiveTimeAxes,...
                                    'xdata', iSession,...
                                    'ydata', SessionDuration,...
                                    'Marker', 'x',...
                                    'Color', 'k');
    
    % Total Water Consumption
    WaterConsumption = sum(ChoiceLeftRight .* [Rewarded; Rewarded] .* RewardMagnitude, 'all', "omitnan") / 1000;
    
    yyaxis(WaterConsumptionAxes, 'left')
    WaterConsumptionLine{iSession} = line(WaterConsumptionAxes,...
                                          'xdata', iSession,...
                                          'ydata', WaterConsumption,...
                                          'Marker', 'x',...
                                          'Color', 'k');
    
    % Water Consumption Rate
    WaterConsumptionRate = WaterConsumption ./ SessionDuration;
    
    yyaxis(WaterConsumptionAxes, 'right')
    WaterConsumptionRateLine{iSession} = line(WaterConsumptionAxes,...
                                              'xdata', iSession,...
                                              'ydata', WaterConsumptionRate,...
                                              'Marker', '+',...
                                              'Color', 'r');
    
    % Left-Right Move Time
    LeftMoveTime = MoveTime(ChoiceLeft == 1);
    LeftMoveTimeSwarmchart{iSession} = swarmchart(LRMoveTimeAxes,...
                                                  ones(size(LeftMoveTime)) * (iSession - 0.2),...
                                                  LeftMoveTime,...
                                                  'SizeData', 5,...
                                                  'Marker', '.',...
                                                  'MarkerEdgeColor', LRPalette(1,:),...
                                                  'XJitter', 'density',...
                                                  'XJitterWidth', 0.4);

    LeftMoveTimeBoxchart{iSession} = boxchart(LRMoveTimeAxes,...
                                              ones(size(LeftMoveTime)) * (iSession - 0.2),...
                                              LeftMoveTime,...
                                              'BoxWidth', 0.2,...
                                              'BoxFaceColor', 'k',...
                                              'BoxFaceAlpha', 0,...
                                              'MarkerStyle', 'none',...
                                              'LineWidth', 0.2);
    
    RightMoveTime = MoveTime(ChoiceLeft == 0);
    RightMoveTimeSwarmchart{iSession} = swarmchart(LRMoveTimeAxes,...
                                                   ones(size(RightMoveTime)) * (iSession + 0.2),...
                                                   RightMoveTime,...
                                                   'SizeData', 5,...
                                                   'Marker', '.',...
                                                   'MarkerEdgeColor', LRPalette(2,:),...
                                                   'XJitter', 'density',...
                                                   'XJitterWidth', 0.4);
    
    RightMoveTimeBoxchart{iSession} = boxchart(LRMoveTimeAxes,...
                                               ones(size(RightMoveTime)) * (iSession + 0.2),...
                                               RightMoveTime,...
                                               'BoxWidth', 0.2,...
                                               'BoxFaceColor', 'k',...
                                               'BoxFaceAlpha', 0,...
                                               'MarkerStyle', 'none',...
                                               'LineWidth', 0.2);
    
    % Left-Right Time Investment (NotBaited Waiting Time)
    NotBaited = any(~Baited .* ChoiceLeftRight, 1) & (IncorrectChoice ~= 1);
    
    LeftTI = FeedbackWaitingTime(NotBaited == 1 & ChoiceLeft == 1);
    LeftTISwarmchart{iSession} = swarmchart(LRTIAxes,...
                                            ones(size(LeftTI)) * (iSession - 0.2),...
                                            LeftTI,...
                                            'SizeData', 5,...
                                            'Marker', '.',...
                                            'MarkerEdgeColor', LRPalette(1,:),...
                                            'XJitter', 'density',...
                                            'XJitterWidth', 0.4);

    LeftTIBoxchart{iSession} = boxchart(LRTIAxes,...
                                        ones(size(LeftTI)) * (iSession - 0.2),...
                                        LeftTI,...
                                        'BoxWidth', 0.2,...
                                        'BoxFaceColor', 'k',...
                                        'BoxFaceAlpha', 0,...
                                        'MarkerStyle', 'none',...
                                        'LineWidth', 0.2);
    
    RightTI = FeedbackWaitingTime(NotBaited == 1 & ChoiceLeft == 0);
    RightTISwarmchart{iSession} = swarmchart(LRTIAxes,...
                                             ones(size(RightTI)) * (iSession + 0.2),...
                                             RightTI,...
                                             'SizeData', 5,...
                                             'Marker', '.',...
                                             'MarkerEdgeColor', LRPalette(2,:),...
                                             'XJitter', 'density',...
                                             'XJitterWidth', 0.4);

    RightTIBoxchart{iSession} = boxchart(LRTIAxes,...
                                         ones(size(RightTI)) * (iSession + 0.2),...
                                         RightTI,...
                                         'BoxWidth', 0.2,...
                                         'BoxFaceColor', 'k',...
                                         'BoxFaceAlpha', 0,...
                                         'MarkerStyle', 'none',...
                                         'LineWidth', 0.2);
    
    % Trial Length
    TrialLength = TrialLength(~NoTrialStart);
    TrialLengthSwarmchart{iSession} = swarmchart(TrialLengthAxes,...
                                                 ones(size(TrialLength)) * iSession,...
                                                 TrialLength,...
                                                 'SizeData', 5,...
                                                 'Marker', '.',...
                                                 'MarkerEdgeColor', [0.5 0.5 0.5],...
                                                 'XJitter', 'density',...
                                                 'XJitterWidth', 0.4);

    % NoTrialStart Rate across session
    SkippedBaited = any(Baited .* ChoiceLeftRight .* [SkippedFeedback; SkippedFeedback], 1) & (IncorrectChoice ~= 1);
    SkippedBaitedLine{iSession} = line(SkippedBaitedAxes,...
                                       'xdata', iSession,...
                                       'ydata', sum(SkippedBaited == 1) ./ sum(ActiveTrial == 1) * 100,...
                                       'Marker', '+',...
                                       'Color', neon_purple);
    
    % colour palette for cues: (1- P(r)) * 128 + 127
    % P(0) = white; P(1) = smoky gray
    RewardProbCategories = unique(RewardProb);
    CuedPalette = ((1 - RewardProbCategories) * [128 128 128] + 127)/255;
    
    LightLeftRight = [LightLeft; 1 - LightLeft];
    TrialRewardProb = sum(RewardProb .* LightLeftRight, 1);
    
    for iRewardProb = 1:length(RewardProbCategories)
        TargetRewardProb = RewardProbCategories(iRewardProb);
        Colour = CuedPalette(iRewardProb, :);

        % Cued-sorted Move Time (only correct choice)
        ValidTrial = TrialRewardProb == TargetRewardProb & IncorrectChoice == 0;
        
        CueSortedMoveTime = MoveTime(ValidTrial);
        CueSortedMoveTimeSwarmchart{end + 1} = swarmchart(CueSortedMoveTimeAxes,...
                                                          ones(size(CueSortedMoveTime)) * (iSession + (TargetRewardProb - 0.5) * 0.4),...
                                                          CueSortedMoveTime,...
                                                          'SizeData', 5,...
                                                          'Marker', '.',...
                                                          'MarkerEdgeColor', Colour,...
                                                          'XJitter', 'density',...
                                                          'XJitterWidth', 0.4);
    
        CueSortedMoveTimeBoxchart{end + 1} = boxchart(CueSortedMoveTimeAxes,...
                                                      ones(size(CueSortedMoveTime)) * (iSession + (TargetRewardProb - 0.5) * 0.4),...
                                                      CueSortedMoveTime,...
                                                      'BoxWidth', 0.2,...
                                                      'BoxFaceColor', 'k',...
                                                      'BoxFaceAlpha', 0,...
                                                      'MarkerStyle', 'none',...
                                                      'LineWidth', 0.2);
        
        % Cued-sorted Time Investment (NotBaited Waiting Time)
        ValidTrial = TrialRewardProb == TargetRewardProb & NotBaited == 1;
        
        CueSortedTI = FeedbackWaitingTime(ValidTrial);
        CueSortedTISwarmchart{end + 1} = swarmchart(CueSortedTIAxes,...
                                                    ones(size(CueSortedTI)) * (iSession + (TargetRewardProb - 0.5) * 0.4),...
                                                    CueSortedTI,...
                                                    'SizeData', 5,...
                                                    'Marker', '.',...
                                                    'MarkerEdgeColor', Colour,...
                                                    'XJitter', 'density',...
                                                    'XJitterWidth', 0.4);
    
        CueSortedTIBoxchart{end + 1} = boxchart(CueSortedTIAxes,...
                                                ones(size(CueSortedTI)) * (iSession + (TargetRewardProb - 0.5) * 0.4),...
                                                CueSortedTI,...
                                                'BoxWidth', 0.2,...
                                                'BoxFaceColor', 'k',...
                                                'BoxFaceAlpha', 0,...
                                                'MarkerStyle', 'none',...
                                                'LineWidth', 0.2);

    end
end

%% Trial average across sessions
% NoTrialStart Rate across session
AverageNoTrialStart = NoTrialStartYData(1:iSession, :);
AverageNoTrialStart = mean(AverageNoTrialStart);
AverageNoTrialStart = AverageNoTrialStart(AverageNoTrialStart ~= 100);

NoTrialStartLine{iSession + 1} = line(NoTrialStartAxes,...
                                      'xdata', 1:length(AverageNoTrialStart),...
                                      'ydata', smooth(AverageNoTrialStart),...
                                      'LineStyle', '-',...
                                      'Marker', 'none',...
                                      'Color', 'k');

% WithChoice Rate across session
AverageWithChoiceRate = WithChoiceYData(1:iSession, :);
AverageWithChoiceRate = mean(AverageWithChoiceRate);
AverageWithChoiceRate = AverageWithChoiceRate(AverageWithChoiceRate ~= 0);

WithChoiceLine{iSession + 1} = line(WithChoiceAxes,...
                                    'xdata', 1:length(AverageWithChoiceRate),...
                                    'ydata', smooth(AverageWithChoiceRate),...
                                    'LineStyle', '-',...
                                    'Marker', 'none',...
                                    'Color', 'k');

% SkippedBaited Rate across session
set(SkippedBaitedAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', SessionDateLabel,...
    'XTickLabelRotation', 90);

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

DataPath = strcat(DataFolderPath, '\', FigureTitle, '.png');
exportgraphics(AnalysisFigure, DataPath);

end % function