function EstimatedParameters = TwoArmBanditVariant_Matching_MS_B_ChoiceSymmetricQLearning(DataFolderPath, Prior)
% MS = MultiSession
% B = Bayesian <- Prior using simulation & MCMC (Hamiltonian MC) sampling
% from prior to get marginal posterior
% Matching Analysis Function
% Developed by Antonio Lee @ BCCN Berlin
% Version 1.0 ~ Jan 2025
% Model iteration see the end of script

%% load files
if nargin < 1
    DataFolderPath = uigetdir(OttLabDataServerFolderPath());
elseif ~ischar(DataFolderPath) && ~isstring(DataFolderPath)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

try
    load(fullfile(DataFolderPath, '\Selected_Data.mat'));
    load(fullfile(DataFolderPath, '\Concatenated_Data.mat'));
catch
    disp('Error: Selected DataFolderPath does not contain the required .mat for further steps.')
    return
end

SessionDateRange = DataFolderPath(end-16:end);
[~, RatName] = fileparts(fileparts(fileparts(DataFolderPath)));

RatID = str2double(RatName);
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);

AnalysisName = 'Matching_MS_B_ChoiceSymmetricQLearning';

%% Hierarchaical Symmetric Q-Learning with Forgetting and Stickiness model
% Parametric Prior
% 20241220 tested with simulation that works well as initial parameters
if nargin < 2
    Prior.LearningRateAlpha = 1; % beta distribution beta(1, 1) = uniform distribution
    Prior.LearningRateBeta = 1;
    
    Prior.InverseTemperatureMean = 8; % normal distribution (can be neg. but fully)
    Prior.InverseTemperatureSigma = 1; % N(8, 1) <- from simulation
    
    Prior.ForgettingRateAlpha = 1; % beta distribution beta(1, 1) = uniform distribution
    Prior.ForgettingRateBeta = 1;
    
    Prior.ChoiceStickinessMean = -1; % normal distribution (can be neg. but fully)
    Prior.ChoiceStickinessSigma = 0.2; % N(-1, 0.2) <- from simulation
    
    Prior.ChoiceForgettingRateAlpha = 1; % beta distribution beta(1, 1) = uniform distribution
    Prior.ChoiceForgettingRateBeta = 1;
    
    Prior.BiasMean = 0; % normal distribution
    Prior.BiasSigma = 1;

    Prior.BurnIn = 200;
    Prior.nSample = 2000;

elseif fieldnames(Prior)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

Prior.LearningRateAlpha = 28; % beta distribution beta(1, 1) = uniform distribution
Prior.LearningRateBeta = 52; % beta(28, 52) gives mean ~ 0.35, SD = 0.05 <- from simulation

Prior.InverseTemperatureMean = 8; % normal distribution (can be neg. but fully)
Prior.InverseTemperatureSigma = 1; % N(8, 1) <- from simulation

Prior.ForgettingRateAlpha = 8; % beta(8, 40) gives mean ~ 0.167, SD ~ 0.05
Prior.ForgettingRateBeta = 40;

Prior.ChoiceStickinessMean = -1; % normal distribution (can be neg. but fully)
Prior.ChoiceStickinessSigma = 0.2; % N(-1, 0.2) <- from simulation

Prior.ChoiceForgettingRateAlpha = 1; % beta(1, 8) gives mean ~0.11, SD ~0.10
Prior.ChoiceForgettingRateBeta = 8;

Prior.BiasMean = 0; % normal distribution
Prior.BiasSigma = 1;

Prior.nChain = 1;
Prior.BurnIn = 1000;
Prior.nSample = 1000;

Model = {};
for iSession = 2:length(DataHolder)
    SessionData = DataHolder{iSession};
    
    Model{iSession} = ModelChoiceSymmetricQWithBayes(SessionData, Prior);

    disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')
end

%% create figure
% create figure
AnalysisFigure = figure('Position', [   0       0    1191     842],... % DIN A3, 72 ppi
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateRange, '_', AnalysisName),...
                        'MenuBar', 'none',...
                        'Resize', 'off');

% spacer for correct saving dimension
FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]);
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

% Figure Info
FigureInfoAxes = axes(AnalysisFigure, 'Position', [0.01    0.98    0.48    0.01]);
set(FigureInfoAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

FigureTitle = strcat(RatName, '_', SessionDateRange, '_', AnalysisName);

FigureTitleText = text(FigureInfoAxes, 0, 0,...
                       FigureTitle,...
                       'FontSize', 14,...
                       'FontWeight','bold',...
                       'Interpreter', 'none');

% colour palette
ColourPalette = CommonColourPalette();

%%
PredictedChoice = double(PredictedLeftChoiceProb >= 0.5);
PredictedChoice(isnan(ChoiceLeft)) = nan;
SmoothedPredictedChoiceLeft = smooth(PredictedChoice, BinWidth, 'moving','omitnan');
SmoothedPredictedChoicePlot = plot(BlockSwitchAxes, idxTrial, SmoothedPredictedChoiceLeft * 100, '-b', 'LineWidth', 0.2);

ExploringTrial = find(abs(ChoiceLeft - PredictedLeftChoiceProb) >= 0.5);
ExploitingTrial = find(abs(ChoiceLeft - PredictedLeftChoiceProb) < 0.5);
PredictedExplorationChoicePlot = plot(BlockSwitchAxes, ExploringTrial, 110 - PredictedChoice(ExploringTrial) * 120,...
                                      'Color', 'none',...
                                      'Marker', '.',...
                                      'MarkerEdgeColor', ColourPalette.Explore,...
                                      'MarkerSize', 5);

PredictedExploitationChoicePlot = plot(BlockSwitchAxes, ExploitingTrial, PredictedChoice(ExploitingTrial) * 130 - 15,...
                                       'Color', 'none',...
                                       'Marker', '.',...
                                       'MarkerEdgeColor', ColourPalette.Exploit,...
                                       'MarkerSize', 5);

LegendString = {'$\textsf{P(r)}_\textsf{L}$', '$\textsf{P(r)}_\textsf{R}$', '$\textsf{c}_\textsf{smooth}$',...
                '$\hat\textsf{c}_\textsf{smooth}$', '$\hat\textsf{c}_\textsf{explore}$', '$\hat\textsf{c}_\textsf{exploit}$'};

warning('off', 'MATLAB:handle_graphics:exceptions:SceneNode')

BlockSwitchLegend = legend(BlockSwitchAxes, LegendString,...
                           'Position', [0.01    0.70    0.37    0.06],...
                           'NumColumns', 3);
set(BlockSwitchLegend,...
    'Interpreter', 'latex');

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

%% Block switching behaviour across session
BlockSwitchAxes = axes(AnalysisFigure, 'Position', [0.01    0.82    0.37    0.11]);
hold(BlockSwitchAxes, 'on');
if ~isempty(ChoiceLeft) && ~all(isnan(ChoiceLeft))
    idxTrial = 1:nTrials;
    RewardProbLeft = RewardProb(1,:);
    RewardProbRight = RewardProb(2,:);
    RewardProbLeftPlot = plot(BlockSwitchAxes, idxTrial, RewardProbLeft * 100,...
                              'LineStyle', '-',...
                              'Marker', 'none',...
                              'Color', ColourPalette.Left,...
                              'LineWidth', 1);
    RewardProbRightPlot = plot(BlockSwitchAxes, idxTrial, RewardProbRight * 100,...
                               'LineStyle', '-',...
                               'Marker', 'none',...
                               'Color', turquoise,...
                               'LineWidth', 1);

    BinWidth = 10;
    ChoiceLeftSmoothed = smooth(ChoiceLeft, BinWidth, 'moving','omitnan'); %current bin width: 10 trials
    BlockChoicePlot = plot(BlockSwitchAxes, idxTrial, ChoiceLeftSmoothed * 100,...
                           'LineStyle', '-',...
                           'Color', 'k',...
                           'Marker', 'none',...
                           'LineWidth', 1);
    % TrialLeftChoicePlot = plot(BlockSwitchAxes, idxTrial(ChoiceLeft==1), ChoiceLeft(ChoiceLeft==1) * 110 - 5,...
    %                            'LineStyle', 'none',...
    %                            'Marker', '.',...
    %                            'MarkerEdgeColor', sand, ...
    %                            'MarkerSize', 8);
    % TrialRightChoicePlot = plot(BlockSwitchAxes, idxTrial(ChoiceLeft==0), ChoiceLeft(ChoiceLeft==0) * 110 - 5,...
    %                             'LineStyle', 'none',...
    %                             'Marker', '.',...
    %                             'MarkerEdgeColor', turquoise,...
    %                             'MarkerSize', 8);
    
    set(BlockSwitchAxes,...
        'TickDir', 'out',...
        'YLim', [-20 120],...
        'YTick', [0 50 100],...
        'YAxisLocation', 'right',...
        'FontSize', 10);
    xlabel('iTrial')
    ylabel('Left Choices (%)')
    % title('Block switching behaviour')
end

%% psychometric
PsychometricAxes = axes(AnalysisFigure, 'Position', [0.23    0.56    0.15    0.11]);
hold(PsychometricAxes, 'on')

set(PsychometricAxes,...
    'FontSize', 10,...
    'XLim', [-5 5],...
    'YLim', [0, 100],...
    'YAxisLocation', 'right')
title(PsychometricAxes, 'Psychometric')
xlabel('log(odds)')
ylabel('Left Choices (%)')

% Choice Psychometric
ValidTrial = ~isnan(ChoiceLeft); % and EarlyWithdrawal is always 0
ValidLogOdds = LogOdds(ValidTrial);
ValidChoice = ChoiceLeft(ValidTrial);
dvbin = linspace(-max(abs(ValidLogOdds)), max(abs(ValidLogOdds)), 10);
[xdata, ydata, error] = BinData(ValidLogOdds, ValidChoice, dvbin);
vv = ~isnan(xdata) & ~isnan(ydata) & ~isnan(error);

ChoicePsychometricErrorBar = errorbar(PsychometricAxes, xdata(vv), ydata(vv)*100, error(vv)*100,...
                                      'LineStyle', 'none',...
                                      'LineWidth', 1.5,...
                                      'Color', 'k',...
                                      'Marker', 'o',...
                                      'MarkerEdgeColor', 'k');

PsychometricGLM = fitglm(ValidLogOdds, ValidChoice(:), 'Distribution', 'binomial');
PsychometricGLMPlot = plot(PsychometricAxes, xdata, predict(PsychometricGLM, xdata)*100, '-', 'Color', [.5,.5,.5], 'LineWidth', 0.5);

%% Coefficient of Symmetric Q with forgetting and stickiness
ModelParameterAxes = axes(AnalysisFigure, 'Position', [0.04    0.56    0.15    0.11]);
hold(ModelParameterAxes, 'on');

set(ModelParameterAxes, 'FontSize', 10)
title(ModelParameterAxes, 'Q-RL Fitted Parameters')

LearningRateText = text(ModelParameterAxes, 0, 6,...
                        strcat('\alpha = ', sprintf('%5.3f', LearningRate)),...
                        'FontSize', 12,...
                        'Interpreter', 'tex');

InverseTemperatureText = text(ModelParameterAxes, 0, 5,...
                              strcat('\beta = ', sprintf('%5.2f', InverseTemperature)),...
                              'FontSize', 12,...
                              'Interpreter', 'tex');

ForgettingRateText = text(ModelParameterAxes, 0, 4,...
                          strcat('\gamma = ', sprintf('%5.3f', ForgettingRate)),...
                          'FontSize', 12,...
                          'Interpreter', 'tex');

ChoiceStickinessText = text(ModelParameterAxes, 0, 3,...
                            strcat('\phi = ', sprintf('%5.3f', ChoiceStickiness)),...
                            'FontSize', 12,...
                            'Interpreter', 'tex');

ChoiceForgettingRateText = text(ModelParameterAxes, 0, 2,...
                                strcat('c_\gamma = ', sprintf('%5.3f', ChoiceForgettingRate)),...
                                'FontSize', 12,...
                                'Interpreter', 'tex');

BiasText = text(ModelParameterAxes, 0, 1,...
                strcat('bias = ', sprintf('%5.3f', Bias)),...
                'FontSize', 12,...
                'Interpreter', 'tex');

set(ModelParameterAxes,...
    'YLim', [0, 6],...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')
disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

%% Residual Histogram
ResidualHistogramAxes = axes(AnalysisFigure, 'Position', [0.04    0.36    0.15    0.11]);

ResidualHistogram = histogram(ResidualHistogramAxes, ModelResiduals,...
                              'FaceColor', 'b',...
                              'Normalization', 'pdf');

title(ResidualHistogramAxes, 'Histogram of residuals')

%% Residual Histogram
ResidualLaggedAxes = axes(AnalysisFigure, 'Position', [0.23    0.36    0.15    0.11]);

ResidualLaggedScatter = scatter(ResidualLaggedAxes, ModelResiduals(1:end-1), ModelResiduals(2:end),...
                                'SizeData', 1,...
                                'CData', [0, 0, 1]);

title(ResidualLaggedAxes, 'Plot of residuals vs. lagged residuals')
xlabel(ResidualLaggedAxes, 'Residual(t-1)');
ylabel(ResidualLaggedAxes, 'Residual(t)');

set(ResidualLaggedAxes,...
    'box', 'on')

%% Residual Histogram
ResidualFittedAxes = axes(AnalysisFigure, 'Position', [0.04    0.19    0.15    0.11]);

ResidualFittedScatter = scatter(ResidualFittedAxes, PredictedLeftChoiceProb, ModelResiduals,...
                                'SizeData', 1,...
                                'CData', [0, 0, 1]);

title(ResidualFittedAxes, 'Plot of residuals vs. fitted values')
xlabel(ResidualFittedAxes, 'Fitted values');
ylabel(ResidualFittedAxes, 'Residuals');

set(ResidualFittedAxes,...
    'box', 'on')

%% Residual Histogram
ResidualProbabilityAxes = axes(AnalysisFigure, 'Position', [0.23    0.19    0.15    0.11]);

ResidualProbabilityScatter = scatter(ResidualProbabilityAxes, ModelResiduals(ValidTrial), zscore(ModelResiduals(ValidTrial)),...
                                     'SizeData', 1,...
                                     'CData', [0, 0, 1]);

title(ResidualProbabilityAxes, 'Normal probability plot of residuals')
xlabel(ResidualProbabilityAxes, 'Residuals');
ylabel(ResidualProbabilityAxes, 'z-score');

set(ResidualProbabilityAxes,...
    'box', 'on',...
    'YTickLabel', [0.005, 0.1, 0.5, 0.9, 0.995])

if ~all(isnan(FeedbackWaitingTime))
    %% Time Investment (TI) (only NotBaited Waiting Time) across session 
    TrialTIAxes = axes(AnalysisFigure, 'Position', [0.45    0.82    0.37    0.11]);
    hold(TrialTIAxes, 'on');
    
    NotBaited = any(~Baited .* ChoiceLeftRight, 1) & (IncorrectChoice ~= 1);
    Explore = abs(ChoiceLeft - PredictedLeftChoiceProb) >= 0.5;
    Exploit = abs(ChoiceLeft - PredictedLeftChoiceProb) < 0.5;
    
    ExploringTITrial = NotBaited & Explore;
    ExploitingTITrial = NotBaited & Exploit;
    ExploringTI = FeedbackWaitingTime(ExploringTITrial);
    ExploitingTI = FeedbackWaitingTime(ExploitingTITrial);
    
    % NotBaited invested time per explore/exploit across session
    TrialExploringTIPlot = plot(TrialTIAxes, idxTrial(ExploringTITrial), ExploringTI,...
                                'Marker', '.',...
                                'MarkerSize', 4,...
                                'MarkerEdgeColor', carrot,...
                                'Color', 'none');
    
    TrialExploitingTIPlot = plot(TrialTIAxes, idxTrial(ExploitingTITrial), ExploitingTI,...
                                 'Marker', '.',...
                                 'MarkerSize', 4,...
                                 'MarkerEdgeColor', violet,...
                                 'Color', 'none');
    
    VevaiometryLegend = legend(TrialTIAxes, {'Explore', 'Exploit'},...
                               'Box', 'off',...
                               'Position', [0.75    0.90    0.05    0.03]);

    set(TrialTIAxes,...
        'TickDir', 'out',...
        'XLim', BlockSwitchAxes.XLim,...
        'YLim', [0, max(1, SessionData.SettingsFile.GUI.FeedbackDelayMax * 1.5)],...
        'YAxisLocation', 'right',...
        'FontSize', 10);
    ylabel('Invested Time (s)')
    % title('Block switching behaviour')
    
    %% plot vevaiometric      
    VevaiometricAxes = axes(AnalysisFigure, 'Position', [0.89    0.82    0.10    0.11]);
    hold(VevaiometricAxes, 'on')
    
    ExploringLogOdds = LogOdds(ExploringTITrial);
    ExploitingLogOdds = LogOdds(ExploitingTITrial);
    
    ExploringTrialTIScatter = scatter(VevaiometricAxes, ExploringLogOdds, ExploringTI,...
                                      'Marker', '.',...
                                      'MarkerEdgeColor', carrot,...
                                      'SizeData', 18);
    
    ExploitingTrialTIScatter = scatter(VevaiometricAxes, ExploitingLogOdds, ExploitingTI,...
                                       'Marker', '.',...
                                       'MarkerEdgeColor', violet,...
                                       'SizeData', 18);

    [ExploreLineXData, ExploreLineYData] = Binvevaio(ExploringLogOdds, ExploringTI, 10);
    [ExploitLineXData, ExploitLineYData] = Binvevaio(ExploitingLogOdds, ExploitingTI, 10);
    
    ExplorePlot = plot(VevaiometricAxes, ExploreLineXData, ExploreLineYData,...
                       'Color', carrot,...
                       'LineWidth', 1);       
    
    ExploitPlot = plot(VevaiometricAxes, ExploitLineXData, ExploitLineYData,...
                       'Color', violet,...
                       'LineWidth', 1);
    
    set(VevaiometricAxes,...
        'FontSize', 10,...
        'XLim', [-5 5],...
        'YLim', [0 SessionData.SettingsFile.GUI.FeedbackDelayMax * 1.5])
    title(VevaiometricAxes, 'Vevaiometric');
    xlabel(VevaiometricAxes, 'log(odds)');
    % ylabel(VevaiometricAxes, 'Invested Time (s)');
    
    %% Psychometrics of NotBaited Choice with High- and Low-time investment (TI)
    % Time investment is limited to NotBaited trials
    TISortedPsychometricAxes = axes(AnalysisFigure, 'Position', [0.45    0.56    0.15    0.11]);
    hold(TISortedPsychometricAxes, 'on')
    
    TI = FeedbackWaitingTime(NotBaited);
    TImed = median(TI, "omitnan");
    HighTITrial = FeedbackWaitingTime>TImed & NotBaited;
    LowTITrial = FeedbackWaitingTime<=TImed & NotBaited;
    
    [xdata, ydata, error] = BinData(LogOdds(HighTITrial), ChoiceLeft(HighTITrial), dvbin);
    vv = ~isnan(xdata) & ~isnan(ydata) & ~isnan(error);

    HighTIErrorBar = errorbar(TISortedPsychometricAxes, xdata(vv), ydata(vv)*100, error(vv)*100,...
                              'LineStyle', 'none',...
                              'LineWidth', 1,...
                              'Marker', 'o',...
                              'MarkerFaceColor', 'none',...
                              'MarkerEdgeColor', 'k',...
                              'Color', 'k');

    [xdata, ydata, error] = BinData(LogOdds(LowTITrial), ChoiceLeft(LowTITrial), dvbin);
    vv = ~isnan(xdata) & ~isnan(ydata) & ~isnan(error);

    LowTIErrorBar = errorbar(TISortedPsychometricAxes, xdata(vv), ydata(vv)*100, error(vv)*100,...
                             'LineStyle', 'none',...
                             'LineWidth', 1,...
                             'Marker', 'o',...
                             'MarkerFaceColor', 'none',...
                             'MarkerEdgeColor', [0.5 0.5 0.5],...
                             'Color', [0.5 0.5 0.5]);
    
    HighTIGLM = fitglm(LogOdds(HighTITrial), ChoiceLeft(HighTITrial), 'Distribution', 'binomial');
    HighTIGLMPlot = plot(TISortedPsychometricAxes, xdata, predict(HighTIGLM, xdata)*100,...
                         'Marker', 'none',...
                         'Color', 'k',...
                         'LineWidth', 0.5);

    LowTIGLM = fitglm(LogOdds(LowTITrial), ChoiceLeft(LowTITrial), 'Distribution', 'binomial');
    LowTIGLMPlot = plot(TISortedPsychometricAxes, xdata, predict(LowTIGLM, xdata)*100,...
                        'Marker', 'none',...
                        'Color', [0.5, 0.5, 0.5],...
                        'LineWidth', 0.5);
    
    TIPsychometricLegend = legend(TISortedPsychometricAxes, {'High TI','Low TI'},...
                                  'Box', 'off',...
                                  'Position', [0.55    0.57    0.05    0.03]);
    
    set(TISortedPsychometricAxes,...
        'FontSize', 10,...
        'XLim', [-5 5],...
        'YLim', [0, 100])
    title(TISortedPsychometricAxes, 'TI Sorted Psychometric')
    xlabel('log(odds)')
    % ylabel('Left Choices (%)')
    
    %% callibration plot
    CalibrationAxes = axes(AnalysisFigure, 'Position', [0.66    0.56    0.15    0.11]);
    hold(CalibrationAxes, 'on')
    
    Correct = Exploit(NotBaited); %'correct'
    edges = linspace(min(TI), max(TI), 8);
    
    [xdata, ydata, error] = BinData(TI, Correct, edges);
    vv = ~isnan(xdata) & ~isnan(ydata) & ~isnan(error);
    CalibrationErrorBar = errorbar(CalibrationAxes,...
                                   xdata(vv), ydata(vv)*100, error(vv),...
                                   'LineWidth', 2, ...
                                   'Color', 'k');
    
    set(CalibrationAxes,...
        'FontSize', 10,...
        'XLim', [0 SessionData.SettingsFile.GUI.FeedbackDelayMax * 1.5])
    % title(CalibrationHandle, 'Calibration');
    xlabel(CalibrationAxes, 'Invested Time (s)');
    ylabel(CalibrationAxes, 'Exploit Ratio (%)');
    
    %% Time Investment (TI) (only NotBaited Waiting Time) across session 
    LRTrialTIAxes = axes(AnalysisFigure, 'Position', [0.45    0.36    0.37    0.11]);
    hold(LRTrialTIAxes, 'on');
    
    % Smoothed NotBaited invested time per left/right across session
    LeftTITrial = NotBaited & ChoiceLeft==1;
    RightTITrial = NotBaited & ChoiceLeft==0;
    LeftTI = FeedbackWaitingTime(LeftTITrial);
    RightTI = FeedbackWaitingTime(RightTITrial);
    
    TrialLeftTIPlot = plot(LRTrialTIAxes, idxTrial(LeftTITrial), LeftTI,...
                           'LineStyle', 'none',...
                           'Marker', '.',...
                           'MarkerSize', 4,...
                           'MarkerEdgeColor', sand);
    
    TrialRightTIPlot = plot(LRTrialTIAxes, idxTrial(RightTITrial), RightTI,...
                            'LineStyle', 'none',...
                            'Marker', '.',...
                            'MarkerSize', 4,...
                            'MarkerEdgeColor', turquoise);
    
    LRVevaiometryLegend = legend(LRTrialTIAxes, {'Left', 'Right'},...
                                 'Box', 'off',...
                                 'Position', [0.75    0.44    0.05    0.03]);

    set(LRTrialTIAxes,...
        'TickDir', 'out',...
        'XLim', BlockSwitchAxes.XLim,...
        'YLim', [0, max(1, SessionData.SettingsFile.GUI.FeedbackDelayMax * 1.5)],...
        'YAxisLocation', 'right',...
        'FontSize', 10);
    ylabel('Invested Time (s)')
    % title('Block switching behaviour')
    
    %% plot vevaiometric (L/R sorted residuals = abs(ChoiceLeft - P({ChoiceLeft}^))
    LRTIVevaiometricAxes = axes(AnalysisFigure, 'Position', [0.89    0.36    0.10    0.11]);
    hold(LRTIVevaiometricAxes, 'on')
    
    LeftAbsResidual = AbsModelResiduals(LeftTITrial);
    RightAbsResidual = AbsModelResiduals(RightTITrial);
    
    LeftTIScatter = scatter(LRTIVevaiometricAxes, LeftAbsResidual, LeftTI,...
                            'Marker', '.',...
                            'MarkerEdgeColor', sand,...
                            'SizeData', 18);
    
    RightTIScatter = scatter(LRTIVevaiometricAxes, RightAbsResidual, RightTI,...
                             'Marker', '.',...
                             'MarkerEdgeColor', turquoise,...
                             'SizeData', 18);

    [LeftLineXData, LeftLineYData] = Binvevaio(LeftAbsResidual, LeftTI, 10);
    [RightLineXData, RightLineYData] = Binvevaio(RightAbsResidual, RightTI, 10);
    
    LeftTIPlot = plot(LRTIVevaiometricAxes, LeftLineXData, LeftLineYData,...
                      'Color', sand,...
                      'LineWidth', 1);       
    
    RightTIPlot = plot(LRTIVevaiometricAxes, RightLineXData, RightLineYData,...
                       'Color', turquoise,...
                       'LineWidth', 1);
    
    set(LRTIVevaiometricAxes,...
        'FontSize', 10,...
        'XLim', [0 1],...
        'YLim', [0 SessionData.SettingsFile.GUI.FeedbackDelayMax * 1.5])
    title(LRTIVevaiometricAxes, 'LRVevaiometric');
    xlabel(LRTIVevaiometricAxes, 'abs(Residuals)');
end

%% Move Time (MT) across session 
LRTrialMTAxes = axes(AnalysisFigure, 'Position', [0.45    0.19    0.37    0.11]);
hold(LRTrialMTAxes, 'on');

% Smoothed NotBaited invested time per left/right across session
LeftMT = MoveTime(ChoiceLeft==1);
RightMT = MoveTime(ChoiceLeft==0);

TrialLeftMTPlot = plot(LRTrialMTAxes, idxTrial(ChoiceLeft==1), LeftMT,...
                       'LineStyle', 'none',...
                       'Marker', '.',...
                       'MarkerSize', 4,...
                       'MarkerEdgeColor', sand);

TrialRightMTPlot = plot(LRTrialMTAxes, idxTrial(ChoiceLeft==0), RightMT,...
                        'LineStyle', 'none',...
                        'Marker', '.',...
                        'MarkerSize', 4,...
                        'MarkerEdgeColor', turquoise);

% LRMTVevaiometryLegend = legend(LRTrialMTAxes, {'Left', 'Right'},...
%                                'Box', 'off',...
%                                'Position', [0.75    0.35    0.05    0.03]);

set(LRTrialMTAxes,...
    'TickDir', 'out',...
    'XLim', BlockSwitchAxes.XLim,...
    'YLim', [0, 0.5],...
    'YAxisLocation', 'right',...
    'FontSize', 10);
ylabel('Move Time (s)')
% title('Block switching behaviour')

%% plot vevaiometric (L/R sorted residuals = abs(ChoiceLeft - P({ChoiceLeft}^))
LRMTVevaiometricAxes = axes(AnalysisFigure, 'Position', [0.89    0.19    0.10    0.11]);
hold(LRMTVevaiometricAxes, 'on')

LeftAbsResidual = AbsModelResiduals(ChoiceLeft==1);
RightAbsResidual = AbsModelResiduals(ChoiceLeft==0);

LeftMTScatter = scatter(LRMTVevaiometricAxes, LeftAbsResidual, LeftMT,...
                        'Marker', '.',...
                        'MarkerEdgeColor', sand,...
                        'SizeData', 18);

RightMTScatter = scatter(LRMTVevaiometricAxes, RightAbsResidual, RightMT,...
                         'Marker', '.',...
                         'MarkerEdgeColor', turquoise,...
                         'SizeData', 18);

[LeftLineXData, LeftLineYData] = Binvevaio(LeftAbsResidual, LeftMT, 10);
[RightLineXData, RightLineYData] = Binvevaio(RightAbsResidual, RightMT, 10);

LeftMTPlot = plot(LRMTVevaiometricAxes, LeftLineXData, LeftLineYData,...
                'Color', sand,...
                'LineWidth', 1);       

RightMTPlot = plot(LRMTVevaiometricAxes, RightLineXData, RightLineYData,...
                 'Color', turquoise,...
                 'LineWidth', 1);

set(LRMTVevaiometricAxes,...
    'FontSize', 10,...
    'XLim', [0 1],...
    'YLim', [0 0.5])
% title(LRMTVevaiometricAxes, 'LRMTVevaiometric');
xlabel(LRMTVevaiometricAxes, 'abs(Residuals)');

%% saving
DataFolder = OttLabDataServerFolderPath;
RatName = SessionData.Info.Subject;
% %%The following lines doesn't not work, as the timestamp documented
% in the SessionData may not be the same as the one being used for saving
% SessionDate = string(datetime(SessionData.Info.SessionDate), 'yyyyMMdd')';
% SessionTime = string(datetime(SessionData.Info.SessionStartTime_UTC), 'HHmmSS')';
% SessionDateTime = strcat(SessionDate, '_', SessionTime);
DataPath = strcat(DataFolder, RatName, '\bpod_session\', SessionDateTime, '\',...
                  RatName, '_TwoArmBanditVariant_', SessionDateTime, '_Matching_ChoiceSymmetricQLearning.png');
exportgraphics(AnalysisFigure, DataPath);

DataPath = strcat(DataFolder, RatName, '\bpod_graph\',...
                  RatName, '_TwoArmBanditVariant_', SessionDateTime, '_Matching_ChoiceSymmetricQLearning.png');
exportgraphics(AnalysisFigure, DataPath);

close(AnalysisFigure)

end % function