function [NegLogDataLikelihood, Values] = ChoiceBeliefState(Parameters, nTrials, ChoiceLeft, Rewarded)
% fundementally it is learning any correlation between the values of the
% options -> in a way contrary to normal Q-learning and close to
% counterfactual. Here specifically learn a block structure that changes

% Parameters import
LearningRate = Parameters(1); % \alpha
InverseTemperature = Parameters(2); % \beta
ForgettingRate = Parameters(3); % \gamma_V
ChoiceStickiness = Parameters(4); % \phi
ChoiceForgettingRate = Parameters(5); % \gamma_m
StateInverseTemperature = Parameters(6); % \beta_s
InferredStateVolatility = Parameters(7); % P(s2|s1)\hat, assumed symmetric; proper name 'perceived state transition probability'
Bias = Parameters(8); %

% value initialisation
LeftBeingHigherStatePrior = 0.5; % assume no initial bias
LeftBeingHigherStatePosterior = [];
HigherStateRewardProb = 0.4; % assume expert
LowerStateRewardProb = 0.1; % assume expert
LeftRewardProb = 0.25;
RightRewardProb = 0.25;
ChoiceMemory = 0; % m

NegLogDataLikelihood = 0;
ChoiceLeftProb = [];
ChoiceLeftLogOdds = [];

% Likelihood iteration
for iTrial = 1:nTrials
    % decision from values
    ChoiceLeftLogOdds(iTrial)...
        = InverseTemperature...
              * (LeftRewardProb(iTrial) - RightRewardProb(iTrial))...
              + StateInverseTemperature...
              * (2 * LeftBeingHigherStatePrior(iTrial) - 1)...
              * (HigherStateRewardProb - LowerStateRewardProb)...
              + ChoiceStickiness...
              * ChoiceMemory(iTrial)...
              + Bias;

    ChoiceLeftProb(iTrial) = 1 ./ (1 + exp(-ChoiceLeftLogOdds(iTrial)));    
    
    LeftRewardProb(iTrial + 1) = (1 - ForgettingRate) * LeftRewardProb(iTrial);
    RightRewardProb(iTrial + 1) = (1 - ForgettingRate) * RightRewardProb(iTrial);
    ChoiceMemory(iTrial + 1) = (1 - ChoiceForgettingRate) * ChoiceMemory(iTrial);

    % outcome-value conversion
    if ChoiceLeft(iTrial) == 1
        ChoiceLogOdds = ChoiceLeftLogOdds(iTrial);
        NegLogDataLikelihood = NegLogDataLikelihood - log(1 ./ (1 + exp(-ChoiceLogOdds)));
        
        % update option value
        LeftRewardProb(iTrial + 1)...
            = LeftRewardProb(iTrial + 1)...
                  + LearningRate...
                  * (Rewarded(iTrial) - LeftRewardProb(iTrial));
        
        % update posterior belief
        if Rewarded(iTrial) == 1
            LeftBeingHigherStatePosterior(iTrial)...
                = LeftBeingHigherStatePrior(iTrial)...
                      * HigherStateRewardProb...
                      ./ (LeftBeingHigherStatePrior(iTrial)...
                          * HigherStateRewardProb...
                          + (1 - LeftBeingHigherStatePrior(iTrial))...
                          * LowerStateRewardProb);
        else
            LeftBeingHigherStatePosterior(iTrial)...
                = LeftBeingHigherStatePrior(iTrial)...
                      * (1 - HigherStateRewardProb)...
                      ./ (LeftBeingHigherStatePrior(iTrial)...
                          * (1 - HigherStateRewardProb)...
                          + (1 - LeftBeingHigherStatePrior(iTrial))...
                          * (1 - LowerStateRewardProb));
        end
        
        ChoiceMemory(iTrial + 1) =  ChoiceMemory(iTrial + 1) + ChoiceForgettingRate;
        
    elseif ChoiceLeft(iTrial) == 0
        ChoiceLogOdds = -ChoiceLeftLogOdds(iTrial);
        NegLogDataLikelihood = NegLogDataLikelihood - log(1 ./ (1 + exp(-ChoiceLogOdds)));
        
        % update option value
        RightRewardProb(iTrial + 1)...
            = RightRewardProb(iTrial + 1)...
                  + LearningRate...
                  * (Rewarded(iTrial) - RightRewardProb(iTrial));
        
        % update posterior belief
        if Rewarded(iTrial) == 1
            LeftBeingHigherStatePosterior(iTrial)...
                = LeftBeingHigherStatePrior(iTrial)...
                      * LowerStateRewardProb...
                      ./ (LeftBeingHigherStatePrior(iTrial)...
                          * LowerStateRewardProb...
                          + (1 - LeftBeingHigherStatePrior(iTrial))...
                          * HigherStateRewardProb);
        else
            LeftBeingHigherStatePosterior(iTrial)...
                = LeftBeingHigherStatePrior(iTrial)...
                      * (1 - LowerStateRewardProb)...
                      ./ (LeftBeingHigherStatePrior(iTrial)...
                          * (1 - LowerStateRewardProb)...
                          + (1 - LeftBeingHigherStatePrior(iTrial))...
                          * (1 - HigherStateRewardProb));
        end
        
        ChoiceMemory(iTrial + 1) =  ChoiceMemory(iTrial + 1) - ChoiceForgettingRate;
        
    else
        NegLogDataLikelihood = NegLogDataLikelihood;
        
        LeftBeingHigherStatePosterior(iTrial)...
            = LeftBeingHigherStatePrior(iTrial);

        % Un-do the forgetting (?)
        % ChoiceMemory(iTrial + 1) =  ChoiceMemory(iTrial); 
    end
    
    % numerically unstable to calculate the following
    %{
    DiffValue...
        = (LeftRewardProb(iTrial + 1) - RightRewardProb(iTrial + 1))...
           / (2 * LeftBeingHigherStatePosterior(iTrial) - 1);
    
    if isnan(DiffValue) || isinf(DiffValue)
        DiffValue = 0;
    end
    
    HigherStateRewardProb...
            = (LeftRewardProb(iTrial + 1) + RightRewardProb(iTrial + 1)...
               + DiffValue)...
               / 2;

    LowerStateRewardProb...
        = (LeftRewardProb(iTrial + 1) + RightRewardProb(iTrial + 1)...
           - DiffValue)...
           / 2;
    %}

    % lastly update new state prior based on violatility
    LeftBeingHigherStatePrior(iTrial + 1)...
        = (1- InferredStateVolatility)...
              * LeftBeingHigherStatePosterior(iTrial)...
              + InferredStateVolatility...
              * (1 - LeftBeingHigherStatePosterior(iTrial));
    
end % end for-loop

Values.LeftValue = LeftRewardProb(1:nTrials);
Values.RightValue = RightRewardProb(1:nTrials);
Values.LeftBeingHigherStatePrior = LeftBeingHigherStatePrior(1:nTrials);
Values.LeftBeingHigherStatePosterior = LeftBeingHigherStatePosterior(1:nTrials);
Values.ChoiceMemory = ChoiceMemory(1:nTrials);
Values.ChoiceLeftProb = ChoiceLeftProb(1:nTrials);
Values.ChoiceLeftLogOdds = ChoiceLeftLogOdds(1:nTrials);

end % end function