function AnalysisFigure = Matching_MS_B_ChoiceSymmetricQLearning_Diagnosis(DataFolderPath)
% MS = MultiSession
% B = Bayesian <- Prior using simulation & MCMC (Hamiltonian MC) sampling
% from prior to get marginal posterior
% Matching Analysis Function
% Developed by Antonio Lee @ BCCN Berlin
% Version 1.0 ~ Jan 2025
% Model iteration see the end of script

%% load files
if nargin < 1
    DataFolderPath = uigetdir(OttLabDataServerFolderPath());
elseif ~ischar(DataFolderPath) && ~isstring(DataFolderPath)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

try
    load(fullfile(DataFolderPath, '\Selected_Data.mat'));
    load(fullfile(DataFolderPath, '\Concatenated_Data.mat'));
catch
    disp('Error: Selected DataFolderPath does not contain the required .mat for further steps.')
    return
end

SessionDateRange = DataFolderPath(end-16:end);
[~, RatName] = fileparts(fileparts(fileparts(DataFolderPath)));

RatID = str2double(RatName);
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);

AnalysisName = 'Matching_MS_B_ChoiceSymmetricQLearning';

%% Hierarchaical Symmetric Q-Learning with Forgetting and Stickiness model
try
    load(fullfile(DataFolderPath, strcat('\', AnalysisName, '.mat')));
catch
    disp('Error: no models are found')
    return
end

if ~exist('Models', 'var')
    disp('Error: Loaded data is not a Models')
    return
end

%% create figure
% create figure
AnalysisFigure = figure('Position', [   0       0    1191     842],... % DIN A3, 72 ppi
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateRange, '_', AnalysisName),...
                        'MenuBar', 'none',...
                        'Resize', 'off');

% spacer for correct saving dimension
FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]);
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

% Figure Info
FigureInfoAxes = axes(AnalysisFigure, 'Position', [0.01    0.98    0.48    0.01]);
set(FigureInfoAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

FigureTitle = strcat(RatName, '_', SessionDateRange, '_', AnalysisName, '_Diagnosis');

FigureTitleText = text(FigureInfoAxes, 0, 0,...
                       FigureTitle,...
                       'FontSize', 14,...
                       'FontWeight','bold',...
                       'Interpreter', 'none');

% colour palette
ColourPalette = CommonColourPalette();

%% Analysis across sessions
SessionDateLabel = [];
nSessions = length(DataHolder);

% Posterior mode (i.e. MAP, maximum a posteriori) estimate of ChoiceSymmetricQ
% Photometry site vs non-photometry vs day-of-week (vs estrus if female)
MAPEstimateXTicks = {'all', 'cable at left', 'cable at right', 'cable at both', 'day 1 post-water out', 'estrus', 'metestrus'};

LearningRateMAPAxes = axes(AnalysisFigure, 'Position', [0.05    0.77    0.10    0.16]);
hold(LearningRateMAPAxes, 'on');

LearningRateMAPs = nan(1, nSessions);

set(LearningRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(LearningRateMAPAxes, '\alpha (a.u.)')
title(LearningRateMAPAxes, 'MAP estimate')

InverseTemperatureMAPAxes = axes(AnalysisFigure, 'Position', [0.05    0.57    0.10    0.16]);
hold(InverseTemperatureMAPAxes, 'on');

InverseTemperatureMAPs = nan(1, nSessions);

set(InverseTemperatureMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(InverseTemperatureMAPAxes, '\beta (a.u.)')

ForgettingRateMAPAxes = axes(AnalysisFigure, 'Position', [0.05    0.38    0.10    0.16]);
hold(ForgettingRateMAPAxes, 'on');

ForgettingRateMAPs = nan(1, nSessions);

set(ForgettingRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', MAPEstimateXTicks,...
    'XTickLabelRotation', 90,...
    'YAxisLocation', 'left')
ylabel(ForgettingRateMAPAxes, '\gamma_v (a.u.)')

ChoiceStickinessMAPAxes = axes(AnalysisFigure, 'Position', [0.20    0.77    0.10    0.16]);
hold(ChoiceStickinessMAPAxes, 'on');

ChoiceStickinessMAPs = nan(1, nSessions);

set(ChoiceStickinessMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(ChoiceStickinessMAPAxes, '\phi (a.u.)')

ChoiceForgettingRateMAPAxes = axes(AnalysisFigure, 'Position', [0.20    0.57    0.10    0.16]);
hold(ChoiceForgettingRateMAPAxes, 'on');

ChoiceForgettingRateMAPs = nan(1, nSessions);

set(ChoiceForgettingRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', {},...
    'YAxisLocation', 'left')
ylabel(ChoiceForgettingRateMAPAxes, '\gamma_m (a.u.)')

BiasMAPAxes = axes(AnalysisFigure, 'Position', [0.20    0.38    0.10    0.15]);
hold(BiasMAPAxes, 'on');

BiasMAPs = nan(1, nSessions);

set(BiasMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [-1, 6],...
    'XTick', 0:5,...
    'XTickLabel', MAPEstimateXTicks,...
    'XTickLabelRotation', 90,...
    'YAxisLocation', 'left')
ylabel(BiasMAPAxes, 'bias (a.u.)')

%% residual distribution overview
SessionResidualDistributionAxes = axes(AnalysisFigure, 'Position', [0.35    0.15    0.64    0.09]);
hold(SessionResidualDistributionAxes, 'on')

SessionIdx = [];
Residuals = [];

set(SessionResidualDistributionAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YLim', [-1, 1],...
    'YAxisLocation', 'left')
ylabel(SessionResidualDistributionAxes, 'Residuals (a.u.)')

%% MAP overview
% inverse temperature
SessionLearningRateMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.86    0.64    0.10]);
hold(SessionLearningRateMAPAxes, 'on')

set(SessionLearningRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionLearningRateMAPAxes, '\alpha (a.u.)')

% inverse temperature
SessionInverseTemperatureMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.74    0.64    0.10]);
hold(SessionInverseTemperatureMAPAxes, 'on')

set(SessionInverseTemperatureMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionInverseTemperatureMAPAxes, '\beta (a.u.)')

% forgetting rate
SessionForgettingRateMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.62    0.64    0.10]);
hold(SessionForgettingRateMAPAxes, 'on')

set(SessionForgettingRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionForgettingRateMAPAxes, '\gamma_v (a.u.)')

% choice stickiness
SessionChoiceStickinessMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.50    0.64    0.10]);
hold(SessionChoiceStickinessMAPAxes, 'on')

set(SessionChoiceStickinessMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionChoiceStickinessMAPAxes, '\phi (a.u.)')

% choice forgetting rate
SessionChoiceForgettingRateMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.38    0.64    0.10]);
hold(SessionChoiceForgettingRateMAPAxes, 'on')

set(SessionChoiceForgettingRateMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionChoiceForgettingRateMAPAxes, '\gamma_m (a.u.)')

% bias
SessionBiasMAPAxes = axes(AnalysisFigure, 'Position', [0.35    0.26    0.64    0.10]);
hold(SessionBiasMAPAxes, 'on')

set(SessionBiasMAPAxes,...
    'FontSize', 10,...
    'TickDir', 'out',...
    'XLim', [0 length(DataHolder)+1],...
    'XTickLabel', [],...
    'YAxisLocation', 'left')
ylabel(SessionBiasMAPAxes, 'Bias (a.u.)')

%% SessionMeta
OpticCableTag = nan(1, length(DataHolder)); % nan: non-photo, 1:left, 2:right, 3: both
WeekdayTag = nan(1, length(DataHolder)); % 1: Sunday...
EstrousTag = nan(1, length(DataHolder)); % 0: oestrus, 1: metestrus,...

%% Plotting
for iSession = 1:length(DataHolder)
    % Import SessionData
    SessionData = DataHolder{iSession};
    SessionDateLabel = [SessionDateLabel, string(datestr(datetime(SessionData.Info.SessionDate), 'YYYYmmDD(ddd)'))];
    
    nTrials = SessionData.nTrials;
    if nTrials < 200
        disp(['Session ', num2str(iSession), ' has nTrial < 200. Impossible for analysis.'])
        continue
    end
    
    % check optic cable site for tagging
    if isfield(SessionData.Custom.SessionMeta, 'PhotometryBrainArea')
        if contains(SessionData.Custom.SessionMeta.PhotometryBrainArea, 'eft')
            OpticCableTag(iSession) = 1;
        elseif contains(SessionData.Custom.SessionMeta.PhotometryBrainArea, 'ight')
            OpticCableTag(iSession) = 2;
        end
    elseif isfield(SessionData.Custom.SessionMeta, 'OptoCh3BrainAreas')
        if contains(SessionData.Custom.SessionMeta.OptoCh3BrainAreas, 'eft')
            if contains(SessionData.Custom.SessionMeta.OptoCh3BrainAreas, 'ight')
                OpticCableTag(iSession) = 3;
            else
                OpticCableTag(iSession) = 1;
            end
        elseif contains(SessionData.Custom.SessionMeta.OptoCh3BrainAreas, 'ight')
            OpticCableTag(iSession) = 2;
        end
    end

    % check weekday for tagging
    WeekdayTag(iSession) = weekday(SessionData.Info.SessionDate);
    
    % check oestrual cycle for tagging
    if isfield(SessionData.Custom.SessionMeta, 'EstrousPhase') && ~isempty(SessionData.Custom.SessionMeta.EstrousPhase)
        EstrousTag(iSession) = str2num(SessionData.Custom.SessionMeta.EstrousPhase);
    end
    
    ChoiceLeft = SessionData.Custom.TrialData.ChoiceLeft(1:nTrials);
    Rewarded = SessionData.Custom.TrialData.Rewarded(1:nTrials);

    %% Analysis across sessions
    Model = Models{iSession};
    Chain = vertcat(Model.Chains{:});
    
    [ProbDensity, Values] = ksdensity(Chain(:, 1));
    LearningRateMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    [ProbDensity, Values] = ksdensity(Chain(:, 2));
    InverseTemperatureMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    [ProbDensity, Values] = ksdensity(Chain(:, 3));
    ForgettingRateMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    [ProbDensity, Values] = ksdensity(Chain(:, 4));
    ChoiceStickinessMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    [ProbDensity, Values] = ksdensity(Chain(:, 5));
    ChoiceForgettingRateMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    [ProbDensity, Values] = ksdensity(Chain(:, 6));
    BiasMAPs(iSession) = Values(ProbDensity == max(ProbDensity));
    
    MAPEstimates = [LearningRateMAPs(iSession), InverseTemperatureMAPs(iSession), ForgettingRateMAPs(iSession),...
                    ChoiceStickinessMAPs(iSession), ChoiceForgettingRateMAPs(iSession), BiasMAPs(iSession)];
    
    [NegLogDataLikelihood, Values] = ChoiceSymmetricQLearning(MAPEstimates, nTrials, ChoiceLeft, Rewarded);
    LogOdds = InverseTemperatureMAPs(iSession) * (Values.LeftValue - Values.RightValue) +...
              + ChoiceStickinessMAPs(iSession) * Values.ChoiceMemory + BiasMAPs(iSession);
    
    PredictedLeftChoiceProb = 1 ./ (1 + exp(-LogOdds));

    PredictedChoice = double(PredictedLeftChoiceProb>=0.5);
    PredictedChoice(isnan(ChoiceLeft)) = nan;
    
    Explore = abs(ChoiceLeft - PredictedLeftChoiceProb) >= 0.5;
    Exploit = abs(ChoiceLeft - PredictedLeftChoiceProb) < 0.5;
    
    AbsModelResiduals = abs(ChoiceLeft - PredictedLeftChoiceProb);

    %% session residuals overview
    SessionIdx = [SessionIdx, iSession .* ones(1, nTrials)];
    Residuals = [Residuals, ChoiceLeft - PredictedLeftChoiceProb];
    
    %% session chain summary
    % learning rate
    LearningRateChainSwarmchart(iSession)...
        = swarmchart(SessionLearningRateMAPAxes,...
                     iSession * ones(size(Chain(:, 1))),...
                     Chain(:, 1),...
                     'Marker', '.',...
                     'MarkerEdgeColor', ColourPalette.Session,...
                     'XJitter', 'density',...
                     'XJitterWidth', 0.5);

    LearningRateChainHDILine(iSession)...
        = line(SessionLearningRateMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(1), Model.Diags.Q95(1)],...
               'Color', 'k',...
               'LineWidth', 2);
    
    % inverse temperature
    InverseTemperatureChainSwarmchart(iSession)...
        = swarmchart(SessionInverseTemperatureMAPAxes,...
                     iSession * ones(size(Chain(:, 2))),...
                     Chain(:, 2),...
                     'Marker', '.',...
                     'MarkerEdgeColor', ColourPalette.Session,...
                     'XJitter', 'density',...
                     'XJitterWidth', 0.5);

    InverseTemperatureChainHDILine(iSession)...
        = line(SessionInverseTemperatureMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(2), Model.Diags.Q95(2)],...
               'Color', 'k',...
               'LineWidth', 2);

    % forgetting rate
    ForgettingRateChainSwarmchart(iSession)...
        = swarmchart(SessionForgettingRateMAPAxes,...
                     iSession * ones(size(Chain(:, 3))),...
                     Chain(:, 3),...
                     'Marker', '.',...
                     'MarkerEdgeColor', ColourPalette.Session,...
                     'XJitter', 'density',...
                     'XJitterWidth', 0.5);

    ForgettingRateChainHDILine(iSession)...
        = line(SessionForgettingRateMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(3), Model.Diags.Q95(3)],...
               'Color', 'k',...
               'LineWidth', 2);
    
    % choice stickiness
    ChoiceStickinessChainSwarmchart(iSession)...
        = swarmchart(SessionChoiceStickinessMAPAxes,...
                     iSession * ones(size(Chain(:, 4))),...
                     Chain(:, 4),...
                     'Marker', '.',...
                     'MarkerEdgeColor', ColourPalette.Session,...
                     'XJitter', 'density',...
                     'XJitterWidth', 0.5);

    ChoiceStickinessChainHDILine(iSession)...
        = line(SessionChoiceStickinessMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(4), Model.Diags.Q95(4)],...
               'Color', 'k',...
               'LineWidth', 2);
    
    % choice forgetting rate
    ChoiceForgettingRateChainSwarmchart(iSession)...
        = swarmchart(SessionChoiceForgettingRateMAPAxes,...
                    iSession * ones(size(Chain(:, 5))),...
                    Chain(:, 5),...
                    'Marker', '.',...
                    'MarkerEdgeColor', ColourPalette.Session,...
                    'XJitter', 'density',...
                    'XJitterWidth', 0.5);

    ChoiceForgettingRateChainHDILine(iSession)...
        = line(SessionChoiceForgettingRateMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(5), Model.Diags.Q95(5)],...
               'Color', 'k',...
               'LineWidth', 2);

    % bias
    BiasChainSwarmchart(iSession)...
        = swarmchart(SessionBiasMAPAxes,...
                     iSession * ones(size(Chain(:, 6))),...
                     Chain(:, 6),...
                     'Marker', '.',...
                     'MarkerEdgeColor', ColourPalette.Session,...
                     'XJitter', 'density',...
                     'XJitterWidth', 0.5);

    BiasChainHDILine(iSession)...
        = line(SessionBiasMAPAxes,...
               [iSession, iSession],...
               [Model.Diags.Q5(6), Model.Diags.Q95(6)],...
               'Color', 'k',...
               'LineWidth', 2);
                                                 
end

%% All MAPs
% Posterior mode (i.e. MAP, maximum a posteriori) estimate of ChoiceSymmetricQ
XData = zeros(size(LearningRateMAPs));

% Learning rate
LearningRateSwarmchart...
    = swarmchart(LearningRateMAPAxes,...
                 XData,...
                 LearningRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

LearningRateBoxchart...
    = boxchart(LearningRateMAPAxes, XData, LearningRateMAPs);
set(LearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Inverse temperature
InverseTemperatureSwarmchart...
    = swarmchart(InverseTemperatureMAPAxes,...
                 XData,...
                 InverseTemperatureMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

InverseTemperatureBoxchart...
    = boxchart(InverseTemperatureMAPAxes, XData, InverseTemperatureMAPs);
set(InverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Forgetting rate
ForgettingRateSwarmchart...
    = swarmchart(ForgettingRateMAPAxes,...
                 XData,...
                 ForgettingRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

ForgettingRateBoxchart...
    = boxchart(ForgettingRateMAPAxes, XData, ForgettingRateMAPs);
set(ForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);


% Choice stickiness
ChoiceStickinessSwarmchart...
    = swarmchart(ChoiceStickinessMAPAxes,...
                 XData,...
                 ChoiceStickinessMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

ChoiceStickinessBoxchart...
    = boxchart(ChoiceStickinessMAPAxes, XData, ChoiceStickinessMAPs);
set(ChoiceStickinessBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Choice forgetting rate
ChoiceForgettingRateSwarmchart...
    = swarmchart(ChoiceForgettingRateMAPAxes,...
                 XData,...
                 ChoiceForgettingRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

ChoiceForgettingRateBoxchart...
    = boxchart(ChoiceForgettingRateMAPAxes, XData, ChoiceForgettingRateMAPs);
set(ChoiceForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Bias
BiasSwarmchart...
    = swarmchart(BiasMAPAxes,...
                 XData,...
                 BiasMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

BiasBoxchart = boxchart(BiasMAPAxes, XData, BiasMAPs);
set(BiasBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

%% Left vs Right MAPs
LeftOpticIdx = find(OpticCableTag == 1 | OpticCableTag == 3);
RightOpticIdx = find(OpticCableTag == 2 | OpticCableTag == 3);

% Learning rate
LeftLearningRateMAPPlot...
    = plot(SessionLearningRateMAPAxes, 1:nSessions, LearningRateMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightLearningRateMAPPlot...
    = plot(SessionLearningRateMAPAxes, 1:nSessions, LearningRateMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticLearningRateSwarmchart...
    = swarmchart(LearningRateMAPAxes,...
                 OpticCableTag,...
                 LearningRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticLearningRateBoxchart...
    = boxchart(LearningRateMAPAxes, OpticCableTag, LearningRateMAPs);
set(OpticLearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Inverse temperature
LeftInverseTemperatureMAPPlot...
    = plot(SessionInverseTemperatureMAPAxes, 1:nSessions, InverseTemperatureMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightInverseTemperatureMAPPlot...
    = plot(SessionInverseTemperatureMAPAxes, 1:nSessions, InverseTemperatureMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticInverseTemperatureSwarmchart...
    = swarmchart(InverseTemperatureMAPAxes,...
                 OpticCableTag,...
                 InverseTemperatureMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticInverseTemperatureBoxchart...
    = boxchart(InverseTemperatureMAPAxes, OpticCableTag, InverseTemperatureMAPs);
set(OpticInverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Forgetting rate
LeftForgettingRateMAPPlot...
    = plot(SessionForgettingRateMAPAxes, 1:nSessions, ForgettingRateMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightForgettingRateMAPPlot...
    = plot(SessionForgettingRateMAPAxes, 1:nSessions, ForgettingRateMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticForgettingRateSwarmchart...
    = swarmchart(ForgettingRateMAPAxes,...
                 OpticCableTag,...
                 ForgettingRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticForgettingRateBoxchart...
    = boxchart(ForgettingRateMAPAxes, OpticCableTag, ForgettingRateMAPs);
set(OpticForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Choice stickiness
LeftChoiceStickinessMAPPlot...
    = plot(SessionChoiceStickinessMAPAxes, 1:nSessions, ChoiceStickinessMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightChoiceStickinessMAPPlot...
    = plot(SessionChoiceStickinessMAPAxes, 1:nSessions, ChoiceStickinessMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticChoiceStickinessSwarmchart...
    = swarmchart(ChoiceStickinessMAPAxes,...
                 OpticCableTag,...
                 ChoiceStickinessMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticChoiceStickinessBoxchart...
    = boxchart(ChoiceStickinessMAPAxes, OpticCableTag, ChoiceStickinessMAPs);
set(OpticChoiceStickinessBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Choice forgetting rate
LeftChoiceForgettingRateMAPPlot...
    = plot(SessionChoiceForgettingRateMAPAxes, 1:nSessions, ChoiceForgettingRateMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightChoiceForgettingRateMAPPlot...
    = plot(SessionChoiceStickinessMAPAxes, 1:nSessions, ChoiceForgettingRateMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticChoiceForgettingRateSwarmchart...
    = swarmchart(ChoiceForgettingRateMAPAxes,...
                 OpticCableTag,...
                 ChoiceForgettingRateMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticChoiceForgettingRateBoxchart...
    = boxchart(ChoiceForgettingRateMAPAxes, OpticCableTag, ChoiceForgettingRateMAPs);
set(OpticChoiceForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Bias
LeftBiasMAPPlot...
    = plot(SessionBiasMAPAxes, 1:nSessions, BiasMAPs,...
           'Marker', 'x',...
           'MarkerIndices', LeftOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Left);

RightBiasMAPPlot...
    = plot(SessionBiasMAPAxes, 1:nSessions, BiasMAPs,...
           'Marker', '+',...
           'MarkerIndices', RightOpticIdx,...
           'LineStyle', 'none',...
           'Color', ColourPalette.Right);

OpticBiasSwarmchart...
    = swarmchart(BiasMAPAxes,...
                 OpticCableTag,...
                 BiasMAPs,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

OpticBiasBoxchart...
    = boxchart(BiasMAPAxes, OpticCableTag, BiasMAPs);
set(OpticBiasBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

%% Session residuals overview
SessionResidualsSwamchart...
    = swarmchart(SessionResidualDistributionAxes,...
                 SessionIdx,...
                 Residuals,...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

set(SessionResidualDistributionAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', SessionDateLabel,...
    'XTickLabelRotation', 90);

%% session MAP overview
SesionDateDatetime = datetime(SessionDateLabel, 'InputFormat', 'yyyyMMdd(eee)');
SessionDateDiffDays = caldays(caldiff(SesionDateDatetime, 'days'));
WaterDeprivedDayOneIdx = [1, find(SessionDateDiffDays > 1) + 1];
XData = 4 * ones(size(WaterDeprivedDayOneIdx));

% learning rate
Day1LearningRateMAPPlot...
    = plot(SessionLearningRateMAPAxes, 1:nSessions, LearningRateMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

set(SessionLearningRateMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1LearningRateSwarmchart...
    = swarmchart(LearningRateMAPAxes,...
                 XData,...
                 LearningRateMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1LearningRateBoxchart...
    = boxchart(LearningRateMAPAxes, XData, LearningRateMAPs(WaterDeprivedDayOneIdx));
set(Day1LearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Inverse temperature
Day1InverseTemperatureMAPPlot...
    = plot(SessionInverseTemperatureMAPAxes, 1:nSessions, InverseTemperatureMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

set(SessionInverseTemperatureMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1InverseTemperatureSwarmchart...
    = swarmchart(InverseTemperatureMAPAxes,...
                 XData,...
                 InverseTemperatureMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1InverseTemperatureBoxchart...
    = boxchart(InverseTemperatureMAPAxes, XData, InverseTemperatureMAPs(WaterDeprivedDayOneIdx));
set(Day1InverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% forgetting rate
Day1ForgettingRateMAPPlot...
    = plot(SessionForgettingRateMAPAxes, 1:nSessions, ForgettingRateMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

set(SessionForgettingRateMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1ForgettingRateSwarmchart...
    = swarmchart(ForgettingRateMAPAxes,...
                 XData,...
                 ForgettingRateMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1ForgettingRateBoxchart...
    = boxchart(ForgettingRateMAPAxes, XData, ForgettingRateMAPs(WaterDeprivedDayOneIdx));
set(Day1ForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% choice stickiness
Day1ChoiceStickinessMAPPlot...
    = plot(SessionChoiceStickinessMAPAxes, 1:nSessions, ChoiceStickinessMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

set(SessionChoiceStickinessMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1ChoiceStickinessSwarmchart...
    = swarmchart(ChoiceStickinessMAPAxes,...
                 XData,...
                 ChoiceStickinessMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1ChoiceStickinessBoxchart...
    = boxchart(ChoiceStickinessMAPAxes, XData, ChoiceStickinessMAPs(WaterDeprivedDayOneIdx));
set(Day1ChoiceStickinessBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% choice forgetting rate
Day1ChoiceForgettingRateMAPPlot...
    = plot(SessionChoiceForgettingRateMAPAxes, 1:nSessions, ChoiceForgettingRateMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

set(SessionChoiceForgettingRateMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1ChoiceForgettingRateSwarmchart...
    = swarmchart(ChoiceForgettingRateMAPAxes,...
                 XData,...
                 ChoiceForgettingRateMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1ChoiceForgettingRateBoxchart...
    = boxchart(ChoiceForgettingRateMAPAxes, XData, ChoiceForgettingRateMAPs(WaterDeprivedDayOneIdx));
set(Day1ChoiceForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% bias
Day1BiasMAPPlot...
    = plot(SessionBiasMAPAxes, 1:nSessions, BiasMAPs,...
           'Marker', 'o',...
           'MarkerIndices', WaterDeprivedDayOneIdx,...
           'Color', 'k');

set(SessionBiasMAPAxes,...
    'XTick', 1:length(SessionDateLabel),...
    'XTickLabel', {});

Day1BiasSwarmchart...
    = swarmchart(BiasMAPAxes,...
                 XData,...
                 BiasMAPs(WaterDeprivedDayOneIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

Day1BiasBoxchart...
    = boxchart(BiasMAPAxes, XData, BiasMAPs(WaterDeprivedDayOneIdx));
set(Day1BiasBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

%% oestrual cycle
EstrusIdx = find(EstrousTag == 0);
XData = 5 * ones(size(EstrusIdx));

% learning rate
EstrusLearningRateMAPPlot...
    = plot(SessionLearningRateMAPAxes, 1:nSessions, LearningRateMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

EstrusLearningRateSwarmchart...
    = swarmchart(LearningRateMAPAxes,...
                 XData,...
                 LearningRateMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusLearningRateBoxchart...
    = boxchart(LearningRateMAPAxes, XData, LearningRateMAPs(EstrusIdx));
set(EstrusLearningRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% Inverse temperature
EstrusInverseTemperatureMAPPlot...
    = plot(SessionInverseTemperatureMAPAxes, 1:nSessions, InverseTemperatureMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

EstrusInverseTemperatureSwarmchart...
    = swarmchart(InverseTemperatureMAPAxes,...
                 XData,...
                 InverseTemperatureMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusInverseTemperatureBoxchart...
    = boxchart(InverseTemperatureMAPAxes, XData, InverseTemperatureMAPs(EstrusIdx));
set(EstrusInverseTemperatureBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% forgetting rate
EstrusForgettingRateMAPPlot...
    = plot(SessionForgettingRateMAPAxes, 1:nSessions, ForgettingRateMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

EstrusForgettingRateSwarmchart...
    = swarmchart(ForgettingRateMAPAxes,...
                 XData,...
                 ForgettingRateMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusForgettingRateBoxchart...
    = boxchart(ForgettingRateMAPAxes, XData, ForgettingRateMAPs(EstrusIdx));
set(EstrusForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% choice stickiness
EstrusChoiceStickinessMAPPlot...
    = plot(SessionChoiceStickinessMAPAxes, 1:nSessions, ChoiceStickinessMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

EstrusChoiceStickinessSwarmchart...
    = swarmchart(ChoiceStickinessMAPAxes,...
                 XData,...
                 ChoiceStickinessMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusChoiceStickinessBoxchart...
    = boxchart(ChoiceStickinessMAPAxes, XData, ChoiceStickinessMAPs(EstrusIdx));
set(EstrusChoiceStickinessBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% choice forgetting rate
EstrusChoiceForgettingRateMAPPlot...
    = plot(SessionChoiceForgettingRateMAPAxes, 1:nSessions, ChoiceForgettingRateMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'LineStyle', 'none',...
           'Color', 'k');

EstrusChoiceForgettingRateSwarmchart...
    = swarmchart(ChoiceForgettingRateMAPAxes,...
                 XData,...
                 ChoiceForgettingRateMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusChoiceForgettingRateBoxchart...
    = boxchart(ChoiceForgettingRateMAPAxes, XData, ChoiceForgettingRateMAPs(EstrusIdx));
set(EstrusChoiceForgettingRateBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

% bias
EstrusBiasMAPPlot...
    = plot(SessionBiasMAPAxes, 1:nSessions, BiasMAPs,...
           'Marker', 'square',...
           'MarkerIndices', EstrusIdx,...
           'Color', 'k');

EstrusBiasSwarmchart...
    = swarmchart(BiasMAPAxes,...
                 XData,...
                 BiasMAPs(EstrusIdx),...
                 'Marker', '.',...
                 'MarkerEdgeColor', ColourPalette.Session,...
                 'XJitter', 'density',...
                 'XJitterWidth', 1);

EstrusBiasBoxchart...
    = boxchart(BiasMAPAxes, XData, BiasMAPs(EstrusIdx));
set(EstrusBiasBoxchart,...
    'BoxWidth', 0.2,...
    'BoxFaceColor', 'k',...
    'BoxFaceAlpha', 0,...
    'MarkerStyle', 'none',...
    'LineWidth', 0.2);

%% saving
DataPath = strcat(DataFolderPath, '\', FigureTitle, '.png');
exportgraphics(AnalysisFigure, DataPath);

DataPath = strcat(DataFolderPath, '\', FigureTitle, '.fig');
savefig(AnalysisFigure, DataPath);

end % function