function AnalysisFigure = Matching_MS_HB_ChoiceSymmetricQLearning_HyperpriorDiagnosis(DataFolderPath)
% MS = MultiSession
% HB = Hierarchical Bayesian <- find hyperparameters using simulation & MCMC (Hamiltonian MC) sampling
% from hyperparameters to get prior
% Matching Analysis Function
% Developed by Antonio Lee @ BCCN Berlin
% Version 1.0 ~ Dez 2025
% Model iteration see the end of script

%% load files
if nargin < 1
    DataFolderPath = uigetdir(OttLabDataServerFolderPath());
elseif ~ischar(DataFolderPath) && ~isstring(DataFolderPath)
    disp('Error: Unknown input format. No further analysis can be performed.')
    return
end

try
    load(fullfile(DataFolderPath, '\Selected_Data.mat'));
    % load(fullfile(DataFolderPath, '\Concatenated_Data.mat'));
catch
    disp('Error: Selected DataFolderPath does not contain the required .mat for further steps.')
    return
end

SessionDateRange = DataFolderPath(end-16:end);
[~, RatName] = fileparts(fileparts(fileparts(DataFolderPath)));

RatID = str2double(RatName);
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);

AnalysisName = 'Matching_MS_HB_ChoiceSymmetricQLearning';

%% Hierarchaical Symmetric Q-Learning with Forgetting and Stickiness model
try
    load(fullfile(DataFolderPath, strcat('\', AnalysisName, '.mat')));
catch
    disp('Error: no models are found')
    return
end

if ~exist('Model', 'var')
    disp('Error: Loaded data is not a Model')
    return
end

%% create figure
% create figure
AnalysisFigure = figure('Position', [   0       0    1191     842],... % DIN A3, 72 ppi
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateRange, '_', AnalysisName),...
                        'MenuBar', 'none',...
                        'Resize', 'off');

% spacer for correct saving dimension
FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]);
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

% Figure Info
FigureInfoAxes = axes(AnalysisFigure, 'Position', [0.01    0.98    0.48    0.01]);
set(FigureInfoAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'w',...
    'YColor', 'w')

FigureTitle = strcat(RatName, '_', SessionDateRange, '_', AnalysisName, '_Diagnosis');

FigureTitleText = text(FigureInfoAxes, 0, 0,...
                       FigureTitle,...
                       'FontSize', 14,...
                       'FontWeight','bold',...
                       'Interpreter', 'none');

% colour palette
ColourPalette = CommonColourPalette();

%% extract info of the chains
ChainInitialParameters = [Model.ChainInitialParameters{:}];

BurnIn = Model.HyperPrior.BurnIn;
nSample = Model.HyperPrior.nSample;
ChainIdx = (BurnIn + 1):(BurnIn + nSample);

nChain = Model.HyperPrior.nChain;

Chains = Model.Chains;
ConcatenatedChain = vertcat(Model.Chains{:});

%% Chain progression
% learning rate - mu
ChainJdx = 1;
LearningRateMuChainAxes = axes(AnalysisFigure, 'Position', [0.01    0.61    0.28    0.08]);
hold(LearningRateMuChainAxes, 'on');

for iChain = 1:nChain
    LearningRateMuChainPlot(iChain) = plot(LearningRateMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    LearningRateMuBurnInPlot(iChain) = plot(LearningRateMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ChainLegend = legend(LearningRateMuChainAxes, {'iChain', 'iBurnIn'},...
                     'Location', 'northeast',...
                     'NumColumns', 3);

LearningRateMuRHatText...
    = text(LearningRateMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(LearningRateMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
title(LearningRateMuChainAxes, 'Chain')
ylabel(LearningRateMuChainAxes, '\mu_\alpha')

% learning rate - kappa
ChainJdx = 2;
LearningRateKappaChainAxes = axes(AnalysisFigure, 'Position', [0.41    0.61    0.28    0.08]);
hold(LearningRateKappaChainAxes, 'on');

for iChain = 1:nChain
    LearningRateKappaChainPlot(iChain) = plot(LearningRateKappaChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    LearningRateKappaBurnInPlot(iChain) = plot(LearningRateKappaChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

LearningRateKappaRHatText...
    = text(LearningRateKappaChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(LearningRateKappaChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
title(LearningRateKappaChainAxes, 'Chain')
ylabel(LearningRateKappaChainAxes, '\kappa_\alpha')

% inverse temperature - mu
ChainJdx = 3;
InverseTemperatureMuChainAxes = axes(AnalysisFigure, 'Position', [0.01    0.50    0.28    0.08]);
hold(InverseTemperatureMuChainAxes, 'on');

for iChain = 1:nChain
    InverseTemperatureMuChainPlot(iChain) = plot(InverseTemperatureMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    InverseTemperatureMuBurnInPlot(iChain) = plot(InverseTemperatureMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

InverseTemperatureMuRHatText...
    = text(InverseTemperatureMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(InverseTemperatureMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
ylabel(InverseTemperatureMuChainAxes, '\mu_\beta')

% inverse temperature - precision
ChainJdx = 4;
InverseTemperaturePrecisionChainAxes = axes(AnalysisFigure, 'Position', [0.41    0.50    0.28    0.08]);
hold(InverseTemperaturePrecisionChainAxes, 'on');

for iChain = 1:nChain
    InverseTemperaturePrecisionChainPlot(iChain) = plot(InverseTemperaturePrecisionChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    InverseTemperaturePrecisionBurnInPlot(iChain) = plot(InverseTemperaturePrecisionChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

InverseTemperaturePrecisionRHatText...
    = text(InverseTemperaturePrecisionChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(InverseTemperaturePrecisionChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
ylabel(InverseTemperaturePrecisionChainAxes, '$\frac{1}{\sigma_\beta^2}$', 'Interpreter', 'latex')

% forgetting rate - mu chain
ChainJdx = 5;
ForgettingRateMuChainAxes = axes(AnalysisFigure, 'Position', [0.01   0.39    0.28    0.08]);
hold(ForgettingRateMuChainAxes, 'on');

for iChain = 1:nChain
    ForgettingRateMuChainPlot(iChain) = plot(ForgettingRateMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ForgettingRateMuBurnInPlot(iChain) = plot(ForgettingRateMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ForgettingRateMuRHatText...
    = text(ForgettingRateMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ForgettingRateMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
ylabel(ForgettingRateMuChainAxes, '\mu_\gamma_V')

% forgetting rate - kappa
ChainJdx = 6;
ForgettingRateKappaChainAxes = axes(AnalysisFigure, 'Position', [0.41   0.39    0.28    0.08]);
hold(ForgettingRateKappaChainAxes, 'on');

for iChain = 1:nChain
    ForgettingRateKappaChainPlot(iChain) = plot(ForgettingRateKappaChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ForgettingRateKappaBurnInPlot(iChain) = plot(ForgettingRateKappaChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ForgettingRateKappaRHatText...
    = text(ForgettingRateKappaChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ForgettingRateKappaChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
ylabel(ForgettingRateKappaChainAxes, '\kappa_\gamma_V')

% choice stickiness - mu
ChainJdx = 7;
ChoiceStickinessMuChainAxes = axes(AnalysisFigure, 'Position', [0.01   0.28    0.28    0.08]);
hold(ChoiceStickinessMuChainAxes, 'on');

for iChain = 1:nChain
    ChoiceStickinessMuChainPlot(iChain) = plot(ChoiceStickinessMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ChoiceStickinessMuBurnInPlot(iChain) = plot(ChoiceStickinessMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ChoiceStickinessMuRHatText...
    = text(ChoiceStickinessMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ChoiceStickinessMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
ylabel(ChoiceStickinessMuChainAxes, '\mu_\phi')

% choice stickiness - precision
ChainJdx = 8;
ChoiceStickinessPrecisionChainAxes = axes(AnalysisFigure, 'Position', [0.41   0.28    0.28    0.08]);
hold(ChoiceStickinessPrecisionChainAxes, 'on');

for iChain = 1:nChain
    ChoiceStickinessPrecisionChainPlot(iChain) = plot(ChoiceStickinessPrecisionChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ChoiceStickinessPrecisionBurnInPlot(iChain) = plot(ChoiceStickinessPrecisionChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ChoiceStickinessPrecisionRHatText...
    = text(ChoiceStickinessPrecisionChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ChoiceStickinessPrecisionChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
ylabel(ChoiceStickinessPrecisionChainAxes, '$\frac{1}{\sigma_\phi^2}$', 'Interpreter', 'latex')

% choice forgetting rate - mu
ChainJdx = 9;
ChoiceForgettingRateMuChainAxes = axes(AnalysisFigure, 'Position', [0.01   0.17    0.28    0.08]);
hold(ChoiceForgettingRateMuChainAxes, 'on');

for iChain = 1:nChain
    ChoiceForgettingRateMuChainPlot(iChain) = plot(ChoiceForgettingRateMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ChoiceForgettingRateMuBurnInPlot(iChain) = plot(ChoiceForgettingRateMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ChoiceForgettingRateMuRHatText...
    = text(ChoiceForgettingRateMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ChoiceForgettingRateMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
ylabel(ChoiceForgettingRateMuChainAxes, '\mu_\gamma_m')

% choice forgetting rate - kappa
ChainJdx = 10;
ChoiceForgettingRateKappaChainAxes = axes(AnalysisFigure, 'Position', [0.41   0.17    0.28    0.08]);
hold(ChoiceForgettingRateKappaChainAxes, 'on');

for iChain = 1:nChain
    ChoiceForgettingRateKappaChainPlot(iChain) = plot(ChoiceForgettingRateKappaChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    ChoiceForgettingRateKappaBurnInPlot(iChain) = plot(ChoiceForgettingRateKappaChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

ChoiceForgettingRateKappaRHatText...
    = text(ChoiceForgettingRateKappaChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(ChoiceForgettingRateKappaChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
ylabel(ChoiceForgettingRateKappaChainAxes, '\kappa_\gamma_m')

% bias - mu
ChainJdx = 11;
BiasMuChainAxes = axes(AnalysisFigure, 'Position', [0.01   0.06    0.28    0.08]);
hold(BiasMuChainAxes, 'on');

for iChain = 1:nChain
    BiasMuChainPlot(iChain) = plot(BiasMuChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    BiasMuBurnInPlot(iChain) = plot(BiasMuChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

BiasMuRHatText...
    = text(BiasMuChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(BiasMuChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'right',...
    'FontSize', 12);
xlabel(BiasMuChainAxes, 'iSample')
ylabel(BiasMuChainAxes, '\mu_{bias}')

% bias - precision
ChainJdx = 12;
BiasPrecisionChainAxes = axes(AnalysisFigure, 'Position', [0.41   0.06    0.28    0.08]);
hold(BiasPrecisionChainAxes, 'on');

for iChain = 1:nChain
    BiasPrecisionChainPlot(iChain) = plot(BiasPrecisionChainAxes, ChainIdx, Chains{iChain}(:, ChainJdx),...
                                         'Color', ColourPalette.Session);

    BiasPrecisionBurnInPlot(iChain) = plot(BiasPrecisionChainAxes, [0, BurnIn + 1], [ChainInitialParameters(ChainJdx, iChain), Chains{iChain}(1, ChainJdx)],...
                                          'Color', ColourPalette.Session,...
                                          'Marker', 'o',...
                                          'MarkerSize', 4);
    
end

BiasPrecisionRHatText...
    = text(BiasPrecisionChainAxes,...
           0,...
           0.8,...
           strcat('$\hat\textsf{R} = ', sprintf('%5.3f$', Model.Diags.RHat(ChainJdx))),...
           'Units', 'normalized',...
           'Interpreter', 'latex');

set(BiasPrecisionChainAxes,...
    'TickDir', 'out',...
    'XLim', [0, BurnIn + nSample],...
    'XTickLabel', {},...
    'YAxisLocation', 'left',...
    'FontSize', 12);
xlabel(BiasPrecisionChainAxes, 'iSample')
ylabel(BiasPrecisionChainAxes, '$\frac{1}{\sigma_{bias}^2}$', 'Interpreter', 'latex')

disp('YOu aRE a bEAutIFul HUmaN BeiNG, saID anTOniO.')

%% saving
DataPath = strcat(DataFolderPath, '\', FigureTitle, '.png');
exportgraphics(AnalysisFigure, DataPath);

DataPath = strcat(DataFolderPath, '\', FigureTitle, '.fig');
savefig(AnalysisFigure, DataPath);

end % function