function AnalysisFigure = Matching_SS_PhotometryTraces(DataObject, FigureSize, AxeSize)
% for making an example of the task structure
% figure 'unit' set as 'inch' so that we know exactly the meters to pixels
% Developed by Antonio Lee @ BCCN Berlin
% Version 1.0 ~ April 2025

if nargin < 1
    [datafile, datapath] = uigetfile(OttLabDataServerFolderPath());
    load(fullfile(datapath, datafile));
elseif ischar(DataObject) || isstring(DataObject)
    load(DataObject);
else
    DataObject = DataObject;
end

try
    TE = DataObject.LoadProcessedPhotometryFile('TE');
catch
    disp('1st input is not a PhotometryData.mat')
    return
end

%% Load related data to local variabels
SplitedString = split(DataObject.SessionName, '_');
RatID = str2double(SplitedString{1});
if isnan(RatID)
    RatID = -1;
end
RatName = num2str(RatID);
% %%The following three lines doesn't not work, as the timestamp documented
% in the SessionData may not be the same as the one being used for saving
% Date = datestr(SessionData.Info.SessionDate, 'yyyymmdd');

SessionDateTime = strcat(SplitedString{3}, '_', SplitedString{4});

%% Initiatize figure
% create figure
if nargin < 2
    FigureSize = [ 0.2, 0.5, 6.4, 3.6];
end
AnalysisFigure = figure('Position', FigureSize,...
                        'NumberTitle', 'off',...
                        'Name', strcat(RatName, '_', SessionDateTime, '_Matching'),...
                        'MenuBar', 'none',...
                        'Resize', 'off',...
                        'Unit', 'inch',...
                        'Color', 'none');

set(AnalysisFigure,...
    'Position', FigureSize,...
    'unit', 'inch');

FrameAxes = axes(AnalysisFigure, 'Position', [0 0 1 1]); % spacer for correct saving dimension
set(FrameAxes,...
    'XTick', [],...
    'YTick', [],...
    'XColor', 'none',...
    'YColor', 'none',...
    'Color', 'none')

% colour palette
ColourPalette = CommonColourPalette();

%% Photometry DataObject
GreenDemodData = DataObject.LoadProcessedPhotometryFile('Demod', 'Channel', 'Green');
Time = GreenDemodData.Time;
GreenDemodData = GreenDemodData.Data;

RedDemodData = DataObject.LoadProcessedPhotometryFile('Demod', 'Channel', 'Red');
RedDemodData = RedDemodData.Data;

ExampleIdx = 243:245;
AbsoluteTimeTrialStart = TE.AbsoluteTimeTrialStart(ExampleIdx);
AbsoluteTime = AbsoluteTimeTrialStart' + repmat(Time, length(ExampleIdx), 1);
AbsoluteTime = reshape(AbsoluteTime', 1, []);

GreenTraces = reshape(GreenDemodData(ExampleIdx, :)', 1, []);

RedTraces = reshape(RedDemodData(ExampleIdx, :)', 1, []);

%% Background DA
if nargin < 3
    AxeSize = [ 1.2, 0.9, 3.6,  2.4];
end

TracesAxes = axes(AnalysisFigure,...
                  'Position', AxeSize,...
                  'Units', 'inches',...
                  'Color', 'none');
set(TracesAxes,...
    'Position', AxeSize,...
    'Units', 'inches');
hold(TracesAxes, 'on');

%yyaxis(TracesAxes, 'left')

GreenDemodDataPlot = plot(TracesAxes, AbsoluteTime, movmean(GreenTraces, 20),...
                          'LineStyle', '-',...
                          'Color', ColourPalette.Rewarded,...
                          'LineWidth', 1);

set(TracesAxes,...
    'TickDir', 'out',...
    'YColor', ColourPalette.Rewarded,...
    'YLim', [0.44, 0.52],...
    'FontSize', 18);
xlabel(TracesAxes, 'Time (s)')
ylabel(TracesAxes, 'F (a.u.)'); %'GRAB-DA_{3h} (a.u.)')
%{
yyaxis(TracesAxes, 'right')

RedDemodDataPlot = plot(TracesAxes, AbsoluteTime, movmean(RedTraces, 20),...
                        'LineStyle', '-',...
                        'Color', 0.5 * [1, 1, 1],...
                        'LineWidth', 1);
%}
AbsoluteTimeChoice = TE.AbsoluteTimeTrialStart(ExampleIdx) + TE.TimeChoice(ExampleIdx);
TimeChoicePlot = line(TracesAxes, AbsoluteTimeChoice, ones(size(AbsoluteTimeChoice)) * 0.515,...
                      'LineStyle', 'none',...
                      'LineWidth', 2,...
                      'Marker', '|',...
                      'Color', [0, 0, 0]);

AbsoluteTimeReward = TE.AbsoluteTimeTrialStart(ExampleIdx) + TE.TimeReward(ExampleIdx);
TimeRewardPlot = line(TracesAxes, AbsoluteTimeReward, ones(size(AbsoluteTimeReward)) * 0.51,...
                      'LineStyle', 'none',...
                      'LineWidth', 2,...
                      'Marker', '|',...
                      'Color', ColourPalette.Rewarded);

LegendText = {"", "Choice", "Reward"};
TracesLegend = legend(TracesAxes, LegendText,...
                      'Position', [4.5, 2.9, 1.3, 0.6],...
                      'NumColumns', 1,...
                      'Units', 'inches',...
                      'Color', 'w',...
                      'Box', 'on');
set(TracesLegend,...
    'Position', [4.5, 2.9, 1.3, 0.6],...
    'Units', 'inches');
%{
set(TracesAxes,...
    'YColor', 0.5 * [1, 1, 1],...
    'YLim', [0.80, 0.90]);
ylabel(TracesAxes, 'tdTomato (a.u.)')
% title(TracesAxes, 'Example florescence traces')
%}
exportgraphics(AnalysisFigure, strcat(RatName, '_', SessionDateTime, '_Matching_PhotometryTraces_F.pdf'), 'ContentType', 'vector', 'Resolution', 300)
end