Figure = figure();
set(Figure,...
    'Unit', 'inches',...
    'Position', [0.5, 0.5, 3, 3.5]);

Axes = axes(Figure);
set(Axes,...
    'Unit', 'inches',...
    'Position', [0.8, 0.5, 2, 2.5]);

YData = [ForagingRLMinNegLogDataLikelihood; QRLMinNegLogDataLikelihood]';

Plot = plot(Axes, [0, 1], YData, 'Color', 'k', 'Marker', 'o');
set(Axes,...
    'XLim', [-0.5, 1.5],...
    'XTick', [0, 1],...
    'XTickLabel', {'Foraging', 'Q-RL'})
ylabel(Axes,...
       '$-ln\mathcal{L}(\hat\theta, Y)$',...
       'Interpreter', 'latex')

[h,p,ci,stats] = ttest(ForagingRLMinNegLogDataLikelihood, QRLMinNegLogDataLikelihood);
SignificanceText = text(0.5, 550, sprintf('p=%4.2g', p));
set(SignificanceText, 'HorizontalAlignment', 'center')